# coding: utf-8

"""
    TikHub.io - Your Ultimate Social Media Data & API Marketplace

    High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import tikhub_sdk_v2
from tikhub_sdk_v2.api.douyin_xingtu_api_api import DouyinXingtuAPIApi  # noqa: E501
from tikhub_sdk_v2.rest import ApiException


class TestDouyinXingtuAPIApi(unittest.TestCase):
    """DouyinXingtuAPIApi unit test stubs"""

    def setUp(self):
        self.api = tikhub_sdk_v2.api.douyin_xingtu_api_api.DouyinXingtuAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_author_content_hot_comment_keywords_v1_api_v1_douyin_xingtu_author_content_hot_comment_keywords_v1_get(self):
        """Test case for author_content_hot_comment_keywords_v1_api_v1_douyin_xingtu_author_content_hot_comment_keywords_v1_get

        获取kol热词分析内容V1/Get Author Content Hot Comment Keywords V1  # noqa: E501
        """
        pass

    def test_author_content_hot_comment_keywords_v1_api_v1_douyin_xingtu_author_content_hot_comment_keywords_v1_get_0(self):
        """Test case for author_content_hot_comment_keywords_v1_api_v1_douyin_xingtu_author_content_hot_comment_keywords_v1_get_0

        获取kol热词分析内容V1/Get Author Content Hot Comment Keywords V1  # noqa: E501
        """
        pass

    def test_author_hot_comment_tokens_v1_api_v1_douyin_xingtu_author_hot_comment_tokens_v1_get(self):
        """Test case for author_hot_comment_tokens_v1_api_v1_douyin_xingtu_author_hot_comment_tokens_v1_get

        获取kol热词分析评论V1/Get Author Hot Comment Tokens V1  # noqa: E501
        """
        pass

    def test_author_hot_comment_tokens_v1_api_v1_douyin_xingtu_author_hot_comment_tokens_v1_get_0(self):
        """Test case for author_hot_comment_tokens_v1_api_v1_douyin_xingtu_author_hot_comment_tokens_v1_get_0

        获取kol热词分析评论V1/Get Author Hot Comment Tokens V1  # noqa: E501
        """
        pass

    def test_get_xingtu_kolid_by_sec_user_id_api_v1_douyin_xingtu_get_xingtu_kolid_by_sec_user_id_get(self):
        """Test case for get_xingtu_kolid_by_sec_user_id_api_v1_douyin_xingtu_get_xingtu_kolid_by_sec_user_id_get

        根据抖音sec_user_id获取游客星图kolid/Get XingTu kolid by Douyin sec_user_id  # noqa: E501
        """
        pass

    def test_get_xingtu_kolid_by_sec_user_id_api_v1_douyin_xingtu_get_xingtu_kolid_by_sec_user_id_get_0(self):
        """Test case for get_xingtu_kolid_by_sec_user_id_api_v1_douyin_xingtu_get_xingtu_kolid_by_sec_user_id_get_0

        根据抖音sec_user_id获取游客星图kolid/Get XingTu kolid by Douyin sec_user_id  # noqa: E501
        """
        pass

    def test_get_xingtu_kolid_by_uid_api_v1_douyin_xingtu_get_xingtu_kolid_by_uid_get(self):
        """Test case for get_xingtu_kolid_by_uid_api_v1_douyin_xingtu_get_xingtu_kolid_by_uid_get

        根据抖音用户ID获取游客星图kolid/Get XingTu kolid by Douyin User ID  # noqa: E501
        """
        pass

    def test_get_xingtu_kolid_by_uid_api_v1_douyin_xingtu_get_xingtu_kolid_by_uid_get_0(self):
        """Test case for get_xingtu_kolid_by_uid_api_v1_douyin_xingtu_get_xingtu_kolid_by_uid_get_0

        根据抖音用户ID获取游客星图kolid/Get XingTu kolid by Douyin User ID  # noqa: E501
        """
        pass

    def test_get_xingtu_kolid_by_unique_id_api_v1_douyin_xingtu_get_xingtu_kolid_by_unique_id_get(self):
        """Test case for get_xingtu_kolid_by_unique_id_api_v1_douyin_xingtu_get_xingtu_kolid_by_unique_id_get

        根据抖音号获取游客星图kolid/Get XingTu kolid by Douyin unique_id  # noqa: E501
        """
        pass

    def test_get_xingtu_kolid_by_unique_id_api_v1_douyin_xingtu_get_xingtu_kolid_by_unique_id_get_0(self):
        """Test case for get_xingtu_kolid_by_unique_id_api_v1_douyin_xingtu_get_xingtu_kolid_by_unique_id_get_0

        根据抖音号获取游客星图kolid/Get XingTu kolid by Douyin unique_id  # noqa: E501
        """
        pass

    def test_kol_audience_portrait_v1_api_v1_douyin_xingtu_kol_audience_portrait_v1_get(self):
        """Test case for kol_audience_portrait_v1_api_v1_douyin_xingtu_kol_audience_portrait_v1_get

        获取kol观众画像V1/Get kol Audience Portrait V1  # noqa: E501
        """
        pass

    def test_kol_audience_portrait_v1_api_v1_douyin_xingtu_kol_audience_portrait_v1_get_0(self):
        """Test case for kol_audience_portrait_v1_api_v1_douyin_xingtu_kol_audience_portrait_v1_get_0

        获取kol观众画像V1/Get kol Audience Portrait V1  # noqa: E501
        """
        pass

    def test_kol_base_info_v1_api_v1_douyin_xingtu_kol_base_info_v1_get(self):
        """Test case for kol_base_info_v1_api_v1_douyin_xingtu_kol_base_info_v1_get

        获取kol基本信息V1/Get kol Base Info V1  # noqa: E501
        """
        pass

    def test_kol_base_info_v1_api_v1_douyin_xingtu_kol_base_info_v1_get_0(self):
        """Test case for kol_base_info_v1_api_v1_douyin_xingtu_kol_base_info_v1_get_0

        获取kol基本信息V1/Get kol Base Info V1  # noqa: E501
        """
        pass

    def test_kol_conversion_ability_analysis_v1_api_v1_douyin_xingtu_kol_conversion_ability_analysis_v1_get(self):
        """Test case for kol_conversion_ability_analysis_v1_api_v1_douyin_xingtu_kol_conversion_ability_analysis_v1_get

        获取kol转化能力分析V1/Get kol Conversion Ability Analysis V1  # noqa: E501
        """
        pass

    def test_kol_conversion_ability_analysis_v1_api_v1_douyin_xingtu_kol_conversion_ability_analysis_v1_get_0(self):
        """Test case for kol_conversion_ability_analysis_v1_api_v1_douyin_xingtu_kol_conversion_ability_analysis_v1_get_0

        获取kol转化能力分析V1/Get kol Conversion Ability Analysis V1  # noqa: E501
        """
        pass

    def test_kol_convert_video_display_v1_api_v1_douyin_xingtu_kol_convert_video_display_v1_get(self):
        """Test case for kol_convert_video_display_v1_api_v1_douyin_xingtu_kol_convert_video_display_v1_get

        获取kol转化视频展示V1/Get kol Convert Video Display V1  # noqa: E501
        """
        pass

    def test_kol_convert_video_display_v1_api_v1_douyin_xingtu_kol_convert_video_display_v1_get_0(self):
        """Test case for kol_convert_video_display_v1_api_v1_douyin_xingtu_kol_convert_video_display_v1_get_0

        获取kol转化视频展示V1/Get kol Convert Video Display V1  # noqa: E501
        """
        pass

    def test_kol_cp_info_v1_api_v1_douyin_xingtu_kol_cp_info_v1_get(self):
        """Test case for kol_cp_info_v1_api_v1_douyin_xingtu_kol_cp_info_v1_get

        获取kol性价比能力分析V1/Get kol Cp Info V1  # noqa: E501
        """
        pass

    def test_kol_cp_info_v1_api_v1_douyin_xingtu_kol_cp_info_v1_get_0(self):
        """Test case for kol_cp_info_v1_api_v1_douyin_xingtu_kol_cp_info_v1_get_0

        获取kol性价比能力分析V1/Get kol Cp Info V1  # noqa: E501
        """
        pass

    def test_kol_daily_fans_v1_api_v1_douyin_xingtu_kol_daily_fans_v1_get(self):
        """Test case for kol_daily_fans_v1_api_v1_douyin_xingtu_kol_daily_fans_v1_get

        获取kol粉丝趋势V1/Get kol Daily Fnas V1  # noqa: E501
        """
        pass

    def test_kol_daily_fans_v1_api_v1_douyin_xingtu_kol_daily_fans_v1_get_0(self):
        """Test case for kol_daily_fans_v1_api_v1_douyin_xingtu_kol_daily_fans_v1_get_0

        获取kol粉丝趋势V1/Get kol Daily Fnas V1  # noqa: E501
        """
        pass

    def test_kol_data_overview_v1_api_v1_douyin_xingtu_kol_data_overview_v1_get(self):
        """Test case for kol_data_overview_v1_api_v1_douyin_xingtu_kol_data_overview_v1_get

        获取kol数据概览V1/Get kol Data Overview V1  # noqa: E501
        """
        pass

    def test_kol_data_overview_v1_api_v1_douyin_xingtu_kol_data_overview_v1_get_0(self):
        """Test case for kol_data_overview_v1_api_v1_douyin_xingtu_kol_data_overview_v1_get_0

        获取kol数据概览V1/Get kol Data Overview V1  # noqa: E501
        """
        pass

    def test_kol_fans_portrait_v1_api_v1_douyin_xingtu_kol_fans_portrait_v1_get(self):
        """Test case for kol_fans_portrait_v1_api_v1_douyin_xingtu_kol_fans_portrait_v1_get

        获取kol粉丝画像V1/Get kol Fans Portrait V1  # noqa: E501
        """
        pass

    def test_kol_fans_portrait_v1_api_v1_douyin_xingtu_kol_fans_portrait_v1_get_0(self):
        """Test case for kol_fans_portrait_v1_api_v1_douyin_xingtu_kol_fans_portrait_v1_get_0

        获取kol粉丝画像V1/Get kol Fans Portrait V1  # noqa: E501
        """
        pass

    def test_kol_link_struct_v1_api_v1_douyin_xingtu_kol_link_struct_v1_get(self):
        """Test case for kol_link_struct_v1_api_v1_douyin_xingtu_kol_link_struct_v1_get

        获取kol连接用户V1/Get kol Link Struct V1  # noqa: E501
        """
        pass

    def test_kol_link_struct_v1_api_v1_douyin_xingtu_kol_link_struct_v1_get_0(self):
        """Test case for kol_link_struct_v1_api_v1_douyin_xingtu_kol_link_struct_v1_get_0

        获取kol连接用户V1/Get kol Link Struct V1  # noqa: E501
        """
        pass

    def test_kol_rec_videos_v1_api_v1_douyin_xingtu_kol_rec_videos_v1_get(self):
        """Test case for kol_rec_videos_v1_api_v1_douyin_xingtu_kol_rec_videos_v1_get

        获取kol内容表现V1/Get kol Rec Videos V1  # noqa: E501
        """
        pass

    def test_kol_rec_videos_v1_api_v1_douyin_xingtu_kol_rec_videos_v1_get_0(self):
        """Test case for kol_rec_videos_v1_api_v1_douyin_xingtu_kol_rec_videos_v1_get_0

        获取kol内容表现V1/Get kol Rec Videos V1  # noqa: E501
        """
        pass

    def test_kol_service_price_v1_api_v1_douyin_xingtu_kol_service_price_v1_get(self):
        """Test case for kol_service_price_v1_api_v1_douyin_xingtu_kol_service_price_v1_get

        获取kol服务报价V1/Get kol Service Price V1  # noqa: E501
        """
        pass

    def test_kol_service_price_v1_api_v1_douyin_xingtu_kol_service_price_v1_get_0(self):
        """Test case for kol_service_price_v1_api_v1_douyin_xingtu_kol_service_price_v1_get_0

        获取kol服务报价V1/Get kol Service Price V1  # noqa: E501
        """
        pass

    def test_kol_touch_distribution_v1_api_v1_douyin_xingtu_kol_touch_distribution_v1_get(self):
        """Test case for kol_touch_distribution_v1_api_v1_douyin_xingtu_kol_touch_distribution_v1_get

        获取kol连接用户来源V1/Get kol Touch Distribution V1  # noqa: E501
        """
        pass

    def test_kol_touch_distribution_v1_api_v1_douyin_xingtu_kol_touch_distribution_v1_get_0(self):
        """Test case for kol_touch_distribution_v1_api_v1_douyin_xingtu_kol_touch_distribution_v1_get_0

        获取kol连接用户来源V1/Get kol Touch Distribution V1  # noqa: E501
        """
        pass

    def test_kol_video_performance_v1_api_v1_douyin_xingtu_kol_video_performance_v1_get(self):
        """Test case for kol_video_performance_v1_api_v1_douyin_xingtu_kol_video_performance_v1_get

        获取kol视频表现V1/Get kol Video Performance V1  # noqa: E501
        """
        pass

    def test_kol_video_performance_v1_api_v1_douyin_xingtu_kol_video_performance_v1_get_0(self):
        """Test case for kol_video_performance_v1_api_v1_douyin_xingtu_kol_video_performance_v1_get_0

        获取kol视频表现V1/Get kol Video Performance V1  # noqa: E501
        """
        pass

    def test_kol_xingtu_index_v1_api_v1_douyin_xingtu_kol_xingtu_index_v1_get(self):
        """Test case for kol_xingtu_index_v1_api_v1_douyin_xingtu_kol_xingtu_index_v1_get

        获取kol星图指数V1/Get kol Xingtu Index V1  # noqa: E501
        """
        pass

    def test_kol_xingtu_index_v1_api_v1_douyin_xingtu_kol_xingtu_index_v1_get_0(self):
        """Test case for kol_xingtu_index_v1_api_v1_douyin_xingtu_kol_xingtu_index_v1_get_0

        获取kol星图指数V1/Get kol Xingtu Index V1  # noqa: E501
        """
        pass

    def test_search_kol_v1_api_v1_douyin_xingtu_search_kol_v1_get(self):
        """Test case for search_kol_v1_api_v1_douyin_xingtu_search_kol_v1_get

        关键词搜索kol V1/Search Kol V1  # noqa: E501
        """
        pass

    def test_search_kol_v1_api_v1_douyin_xingtu_search_kol_v1_get_0(self):
        """Test case for search_kol_v1_api_v1_douyin_xingtu_search_kol_v1_get_0

        关键词搜索kol V1/Search Kol V1  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
