# coding: utf-8

"""
    TikHub.io - Your Ultimate Social Media Data & API Marketplace

    High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import tikhub_sdk_v2
from tikhub_sdk_v2.api.douyin_app_v1_api_api import DouyinAppV1APIApi  # noqa: E501
from tikhub_sdk_v2.rest import ApiException


class TestDouyinAppV1APIApi(unittest.TestCase):
    """DouyinAppV1APIApi unit test stubs"""

    def setUp(self):
        self.api = tikhub_sdk_v2.api.douyin_app_v1_api_api.DouyinAppV1APIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch_general_search_result_api_v1_douyin_app_v1_fetch_general_search_result_get(self):
        """Test case for fetch_general_search_result_api_v1_douyin_app_v1_fetch_general_search_result_get

        获取指定关键词的综合搜索结果/Get comprehensive search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_general_search_result_api_v1_douyin_app_v1_fetch_general_search_result_get_0(self):
        """Test case for fetch_general_search_result_api_v1_douyin_app_v1_fetch_general_search_result_get_0

        获取指定关键词的综合搜索结果/Get comprehensive search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_hashtag_detail_api_v1_douyin_app_v1_fetch_hashtag_detail_get(self):
        """Test case for fetch_hashtag_detail_api_v1_douyin_app_v1_fetch_hashtag_detail_get

        获取指定话题的详情数据/Get details of specified hashtag  # noqa: E501
        """
        pass

    def test_fetch_hashtag_detail_api_v1_douyin_app_v1_fetch_hashtag_detail_get_0(self):
        """Test case for fetch_hashtag_detail_api_v1_douyin_app_v1_fetch_hashtag_detail_get_0

        获取指定话题的详情数据/Get details of specified hashtag  # noqa: E501
        """
        pass

    def test_fetch_hashtag_search_result_api_v1_douyin_app_v1_fetch_hashtag_search_result_get(self):
        """Test case for fetch_hashtag_search_result_api_v1_douyin_app_v1_fetch_hashtag_search_result_get

        获取指定关键词的话题搜索结果/Get hashtag search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_hashtag_search_result_api_v1_douyin_app_v1_fetch_hashtag_search_result_get_0(self):
        """Test case for fetch_hashtag_search_result_api_v1_douyin_app_v1_fetch_hashtag_search_result_get_0

        获取指定关键词的话题搜索结果/Get hashtag search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_hashtag_video_list_api_v1_douyin_app_v1_fetch_hashtag_video_list_get(self):
        """Test case for fetch_hashtag_video_list_api_v1_douyin_app_v1_fetch_hashtag_video_list_get

        获取指定话题的作品数据/Get video list of specified hashtag  # noqa: E501
        """
        pass

    def test_fetch_hashtag_video_list_api_v1_douyin_app_v1_fetch_hashtag_video_list_get_0(self):
        """Test case for fetch_hashtag_video_list_api_v1_douyin_app_v1_fetch_hashtag_video_list_get_0

        获取指定话题的作品数据/Get video list of specified hashtag  # noqa: E501
        """
        pass

    def test_fetch_hot_brand_search_api_v1_douyin_app_v1_fetch_brand_hot_search_list_detail_get(self):
        """Test case for fetch_hot_brand_search_api_v1_douyin_app_v1_fetch_brand_hot_search_list_detail_get

        获取抖音品牌热榜具体分类数据/Get Douyin brand hot search list detail data  # noqa: E501
        """
        pass

    def test_fetch_hot_brand_search_api_v1_douyin_app_v1_fetch_brand_hot_search_list_detail_get_0(self):
        """Test case for fetch_hot_brand_search_api_v1_douyin_app_v1_fetch_brand_hot_search_list_detail_get_0

        获取抖音品牌热榜具体分类数据/Get Douyin brand hot search list detail data  # noqa: E501
        """
        pass

    def test_fetch_hot_brand_search_category_api_v1_douyin_app_v1_fetch_brand_hot_search_list_get(self):
        """Test case for fetch_hot_brand_search_category_api_v1_douyin_app_v1_fetch_brand_hot_search_list_get

        获取抖音品牌热榜分类数据/Get Douyin brand hot search list data  # noqa: E501
        """
        pass

    def test_fetch_hot_brand_search_category_api_v1_douyin_app_v1_fetch_brand_hot_search_list_get_0(self):
        """Test case for fetch_hot_brand_search_category_api_v1_douyin_app_v1_fetch_brand_hot_search_list_get_0

        获取抖音品牌热榜分类数据/Get Douyin brand hot search list data  # noqa: E501
        """
        pass

    def test_fetch_hot_search_list_api_v1_douyin_app_v1_fetch_hot_search_list_get(self):
        """Test case for fetch_hot_search_list_api_v1_douyin_app_v1_fetch_hot_search_list_get

        获取抖音热搜榜数据/Get Douyin hot search list data  # noqa: E501
        """
        pass

    def test_fetch_hot_search_list_api_v1_douyin_app_v1_fetch_hot_search_list_get_0(self):
        """Test case for fetch_hot_search_list_api_v1_douyin_app_v1_fetch_hot_search_list_get_0

        获取抖音热搜榜数据/Get Douyin hot search list data  # noqa: E501
        """
        pass

    def test_fetch_live_hot_search_list_api_v1_douyin_app_v1_fetch_live_hot_search_list_get(self):
        """Test case for fetch_live_hot_search_list_api_v1_douyin_app_v1_fetch_live_hot_search_list_get

        获取抖音直播热搜榜数据/Get Douyin live hot search list data  # noqa: E501
        """
        pass

    def test_fetch_live_hot_search_list_api_v1_douyin_app_v1_fetch_live_hot_search_list_get_0(self):
        """Test case for fetch_live_hot_search_list_api_v1_douyin_app_v1_fetch_live_hot_search_list_get_0

        获取抖音直播热搜榜数据/Get Douyin live hot search list data  # noqa: E501
        """
        pass

    def test_fetch_music_detail_api_v1_douyin_app_v1_fetch_music_detail_get(self):
        """Test case for fetch_music_detail_api_v1_douyin_app_v1_fetch_music_detail_get

        获取指定音乐的详情数据/Get details of specified music  # noqa: E501
        """
        pass

    def test_fetch_music_detail_api_v1_douyin_app_v1_fetch_music_detail_get_0(self):
        """Test case for fetch_music_detail_api_v1_douyin_app_v1_fetch_music_detail_get_0

        获取指定音乐的详情数据/Get details of specified music  # noqa: E501
        """
        pass

    def test_fetch_music_hot_search_list_api_v1_douyin_app_v1_fetch_music_hot_search_list_get(self):
        """Test case for fetch_music_hot_search_list_api_v1_douyin_app_v1_fetch_music_hot_search_list_get

        获取抖音音乐热榜数据/Get Douyin music hot search list data  # noqa: E501
        """
        pass

    def test_fetch_music_hot_search_list_api_v1_douyin_app_v1_fetch_music_hot_search_list_get_0(self):
        """Test case for fetch_music_hot_search_list_api_v1_douyin_app_v1_fetch_music_hot_search_list_get_0

        获取抖音音乐热榜数据/Get Douyin music hot search list data  # noqa: E501
        """
        pass

    def test_fetch_music_search_result_api_v1_douyin_app_v1_fetch_music_search_result_get(self):
        """Test case for fetch_music_search_result_api_v1_douyin_app_v1_fetch_music_search_result_get

        获取指定关键词的音乐搜索结果/Get music search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_music_search_result_api_v1_douyin_app_v1_fetch_music_search_result_get_0(self):
        """Test case for fetch_music_search_result_api_v1_douyin_app_v1_fetch_music_search_result_get_0

        获取指定关键词的音乐搜索结果/Get music search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_music_video_list_api_v1_douyin_app_v1_fetch_music_video_list_get(self):
        """Test case for fetch_music_video_list_api_v1_douyin_app_v1_fetch_music_video_list_get

        获取指定音乐的视频列表数据/Get video list of specified music  # noqa: E501
        """
        pass

    def test_fetch_music_video_list_api_v1_douyin_app_v1_fetch_music_video_list_get_0(self):
        """Test case for fetch_music_video_list_api_v1_douyin_app_v1_fetch_music_video_list_get_0

        获取指定音乐的视频列表数据/Get video list of specified music  # noqa: E501
        """
        pass

    def test_fetch_one_video_api_v1_douyin_app_v1_fetch_one_video_get(self):
        """Test case for fetch_one_video_api_v1_douyin_app_v1_fetch_one_video_get

        获取单个作品数据/Get single video data  # noqa: E501
        """
        pass

    def test_fetch_one_video_api_v1_douyin_app_v1_fetch_one_video_get_0(self):
        """Test case for fetch_one_video_api_v1_douyin_app_v1_fetch_one_video_get_0

        获取单个作品数据/Get single video data  # noqa: E501
        """
        pass

    def test_fetch_one_video_by_share_url_api_v1_douyin_app_v1_fetch_one_video_by_share_url_get(self):
        """Test case for fetch_one_video_by_share_url_api_v1_douyin_app_v1_fetch_one_video_by_share_url_get

        根据分享链接获取单个作品数据/Get single video data by sharing link  # noqa: E501
        """
        pass

    def test_fetch_one_video_by_share_url_api_v1_douyin_app_v1_fetch_one_video_by_share_url_get_0(self):
        """Test case for fetch_one_video_by_share_url_api_v1_douyin_app_v1_fetch_one_video_by_share_url_get_0

        根据分享链接获取单个作品数据/Get single video data by sharing link  # noqa: E501
        """
        pass

    def test_fetch_user_like_videos_api_v1_douyin_app_v1_fetch_user_like_videos_get(self):
        """Test case for fetch_user_like_videos_api_v1_douyin_app_v1_fetch_user_like_videos_get

        获取用户喜欢作品数据/Get user like video data  # noqa: E501
        """
        pass

    def test_fetch_user_like_videos_api_v1_douyin_app_v1_fetch_user_like_videos_get_0(self):
        """Test case for fetch_user_like_videos_api_v1_douyin_app_v1_fetch_user_like_videos_get_0

        获取用户喜欢作品数据/Get user like video data  # noqa: E501
        """
        pass

    def test_fetch_user_post_videos_api_v1_douyin_app_v1_fetch_user_post_videos_get(self):
        """Test case for fetch_user_post_videos_api_v1_douyin_app_v1_fetch_user_post_videos_get

        获取用户主页作品数据/Get user homepage video data  # noqa: E501
        """
        pass

    def test_fetch_user_post_videos_api_v1_douyin_app_v1_fetch_user_post_videos_get_0(self):
        """Test case for fetch_user_post_videos_api_v1_douyin_app_v1_fetch_user_post_videos_get_0

        获取用户主页作品数据/Get user homepage video data  # noqa: E501
        """
        pass

    def test_fetch_user_search_result_api_v1_douyin_app_v1_fetch_user_search_result_get(self):
        """Test case for fetch_user_search_result_api_v1_douyin_app_v1_fetch_user_search_result_get

        获取指定关键词的用户搜索结果/Get user search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_user_search_result_api_v1_douyin_app_v1_fetch_user_search_result_get_0(self):
        """Test case for fetch_user_search_result_api_v1_douyin_app_v1_fetch_user_search_result_get_0

        获取指定关键词的用户搜索结果/Get user search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_video_comments_api_v1_douyin_app_v1_fetch_video_comments_get(self):
        """Test case for fetch_video_comments_api_v1_douyin_app_v1_fetch_video_comments_get

        获取单个视频评论数据/Get single video comments data  # noqa: E501
        """
        pass

    def test_fetch_video_comments_api_v1_douyin_app_v1_fetch_video_comments_get_0(self):
        """Test case for fetch_video_comments_api_v1_douyin_app_v1_fetch_video_comments_get_0

        获取单个视频评论数据/Get single video comments data  # noqa: E501
        """
        pass

    def test_fetch_video_comments_reply_api_v1_douyin_app_v1_fetch_video_comment_replies_get(self):
        """Test case for fetch_video_comments_reply_api_v1_douyin_app_v1_fetch_video_comment_replies_get

        获取指定视频的评论回复数据/Get comment replies data of specified video  # noqa: E501
        """
        pass

    def test_fetch_video_comments_reply_api_v1_douyin_app_v1_fetch_video_comment_replies_get_0(self):
        """Test case for fetch_video_comments_reply_api_v1_douyin_app_v1_fetch_video_comment_replies_get_0

        获取指定视频的评论回复数据/Get comment replies data of specified video  # noqa: E501
        """
        pass

    def test_fetch_video_search_result_api_v1_douyin_app_v1_fetch_video_search_result_get(self):
        """Test case for fetch_video_search_result_api_v1_douyin_app_v1_fetch_video_search_result_get

        获取指定关键词的视频搜索结果/Get video search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_video_search_result_api_v1_douyin_app_v1_fetch_video_search_result_get_0(self):
        """Test case for fetch_video_search_result_api_v1_douyin_app_v1_fetch_video_search_result_get_0

        获取指定关键词的视频搜索结果/Get video search results of specified keywords  # noqa: E501
        """
        pass

    def test_handler_user_profile_api_v1_douyin_app_v1_handler_user_profile_get(self):
        """Test case for handler_user_profile_api_v1_douyin_app_v1_handler_user_profile_get

        获取指定用户的信息/Get information of specified user  # noqa: E501
        """
        pass

    def test_handler_user_profile_api_v1_douyin_app_v1_handler_user_profile_get_0(self):
        """Test case for handler_user_profile_api_v1_douyin_app_v1_handler_user_profile_get_0

        获取指定用户的信息/Get information of specified user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
