# coding: utf-8

"""
    TikHub.io - Your Ultimate Social Media Data & API Marketplace

    High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import tikhub_sdk_v2
from tikhub_sdk_v2.api.tik_tok_web_api_api import TikTokWebAPIApi  # noqa: E501
from tikhub_sdk_v2.rest import ApiException


class TestTikTokWebAPIApi(unittest.TestCase):
    """TikTokWebAPIApi unit test stubs"""

    def setUp(self):
        self.api = tikhub_sdk_v2.api.tik_tok_web_api_api.TikTokWebAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_douyin_live_room_api_v1_tiktok_web_tiktok_live_room_get(self):
        """Test case for douyin_live_room_api_v1_tiktok_web_tiktok_live_room_get

        提取直播间弹幕/Extract live room danmaku  # noqa: E501
        """
        pass

    def test_douyin_live_room_api_v1_tiktok_web_tiktok_live_room_get_0(self):
        """Test case for douyin_live_room_api_v1_tiktok_web_tiktok_live_room_get_0

        提取直播间弹幕/Extract live room danmaku  # noqa: E501
        """
        pass

    def test_fetch_check_live_alive_api_v1_tiktok_web_fetch_check_live_alive_get(self):
        """Test case for fetch_check_live_alive_api_v1_tiktok_web_fetch_check_live_alive_get

        直播间开播状态检测/Live room start status check  # noqa: E501
        """
        pass

    def test_fetch_check_live_alive_api_v1_tiktok_web_fetch_check_live_alive_get_0(self):
        """Test case for fetch_check_live_alive_api_v1_tiktok_web_fetch_check_live_alive_get_0

        直播间开播状态检测/Live room start status check  # noqa: E501
        """
        pass

    def test_fetch_explore_post_api_v1_tiktok_web_fetch_explore_post_get(self):
        """Test case for fetch_explore_post_api_v1_tiktok_web_fetch_explore_post_get

        获取探索作品数据/Get explore video data  # noqa: E501
        """
        pass

    def test_fetch_explore_post_api_v1_tiktok_web_fetch_explore_post_get_0(self):
        """Test case for fetch_explore_post_api_v1_tiktok_web_fetch_explore_post_get_0

        获取探索作品数据/Get explore video data  # noqa: E501
        """
        pass

    def test_fetch_general_search_api_v1_tiktok_web_fetch_general_search_get(self):
        """Test case for fetch_general_search_api_v1_tiktok_web_fetch_general_search_get

        获取综合搜索列表/Get general search list  # noqa: E501
        """
        pass

    def test_fetch_general_search_api_v1_tiktok_web_fetch_general_search_get_0(self):
        """Test case for fetch_general_search_api_v1_tiktok_web_fetch_general_search_get_0

        获取综合搜索列表/Get general search list  # noqa: E501
        """
        pass

    def test_fetch_live_recommend_api_v1_tiktok_web_fetch_live_recommend_get(self):
        """Test case for fetch_live_recommend_api_v1_tiktok_web_fetch_live_recommend_get

        获取直播间首页推荐列表/Get live room homepage recommendation list  # noqa: E501
        """
        pass

    def test_fetch_live_recommend_api_v1_tiktok_web_fetch_live_recommend_get_0(self):
        """Test case for fetch_live_recommend_api_v1_tiktok_web_fetch_live_recommend_get_0

        获取直播间首页推荐列表/Get live room homepage recommendation list  # noqa: E501
        """
        pass

    def test_fetch_post_comment_api_v1_tiktok_web_fetch_post_comment_get(self):
        """Test case for fetch_post_comment_api_v1_tiktok_web_fetch_post_comment_get

        获取作品的评论列表/Get video comments  # noqa: E501
        """
        pass

    def test_fetch_post_comment_api_v1_tiktok_web_fetch_post_comment_get_0(self):
        """Test case for fetch_post_comment_api_v1_tiktok_web_fetch_post_comment_get_0

        获取作品的评论列表/Get video comments  # noqa: E501
        """
        pass

    def test_fetch_post_comment_reply_api_v1_tiktok_web_fetch_post_comment_reply_get(self):
        """Test case for fetch_post_comment_reply_api_v1_tiktok_web_fetch_post_comment_reply_get

        获取作品的评论回复列表/Get video comment replies  # noqa: E501
        """
        pass

    def test_fetch_post_comment_reply_api_v1_tiktok_web_fetch_post_comment_reply_get_0(self):
        """Test case for fetch_post_comment_reply_api_v1_tiktok_web_fetch_post_comment_reply_get_0

        获取作品的评论回复列表/Get video comment replies  # noqa: E501
        """
        pass

    def test_fetch_post_detail_api_v1_tiktok_web_fetch_post_detail_get(self):
        """Test case for fetch_post_detail_api_v1_tiktok_web_fetch_post_detail_get

        获取单个作品数据/Get single video data  # noqa: E501
        """
        pass

    def test_fetch_post_detail_api_v1_tiktok_web_fetch_post_detail_get_0(self):
        """Test case for fetch_post_detail_api_v1_tiktok_web_fetch_post_detail_get_0

        获取单个作品数据/Get single video data  # noqa: E501
        """
        pass

    def test_fetch_search_keyword_suggest_api_v1_tiktok_web_fetch_search_keyword_suggest_get(self):
        """Test case for fetch_search_keyword_suggest_api_v1_tiktok_web_fetch_search_keyword_suggest_get

        搜索关键字推荐/Search keyword suggest  # noqa: E501
        """
        pass

    def test_fetch_search_keyword_suggest_api_v1_tiktok_web_fetch_search_keyword_suggest_get_0(self):
        """Test case for fetch_search_keyword_suggest_api_v1_tiktok_web_fetch_search_keyword_suggest_get_0

        搜索关键字推荐/Search keyword suggest  # noqa: E501
        """
        pass

    def test_fetch_search_live_api_v1_tiktok_web_fetch_search_live_get(self):
        """Test case for fetch_search_live_api_v1_tiktok_web_fetch_search_live_get

        搜索直播/Search live  # noqa: E501
        """
        pass

    def test_fetch_search_live_api_v1_tiktok_web_fetch_search_live_get_0(self):
        """Test case for fetch_search_live_api_v1_tiktok_web_fetch_search_live_get_0

        搜索直播/Search live  # noqa: E501
        """
        pass

    def test_fetch_search_user_api_v1_tiktok_web_fetch_search_user_get(self):
        """Test case for fetch_search_user_api_v1_tiktok_web_fetch_search_user_get

        搜索用户/Search user  # noqa: E501
        """
        pass

    def test_fetch_search_user_api_v1_tiktok_web_fetch_search_user_get_0(self):
        """Test case for fetch_search_user_api_v1_tiktok_web_fetch_search_user_get_0

        搜索用户/Search user  # noqa: E501
        """
        pass

    def test_fetch_search_video_api_v1_tiktok_web_fetch_search_video_get(self):
        """Test case for fetch_search_video_api_v1_tiktok_web_fetch_search_video_get

        搜索视频/Search video  # noqa: E501
        """
        pass

    def test_fetch_search_video_api_v1_tiktok_web_fetch_search_video_get_0(self):
        """Test case for fetch_search_video_api_v1_tiktok_web_fetch_search_video_get_0

        搜索视频/Search video  # noqa: E501
        """
        pass

    def test_fetch_tag_detail_api_v1_tiktok_web_fetch_tag_detail_get(self):
        """Test case for fetch_tag_detail_api_v1_tiktok_web_fetch_tag_detail_get

        Tag详情/Tag Detail  # noqa: E501
        """
        pass

    def test_fetch_tag_detail_api_v1_tiktok_web_fetch_tag_detail_get_0(self):
        """Test case for fetch_tag_detail_api_v1_tiktok_web_fetch_tag_detail_get_0

        Tag详情/Tag Detail  # noqa: E501
        """
        pass

    def test_fetch_tag_post_api_v1_tiktok_web_fetch_tag_post_get(self):
        """Test case for fetch_tag_post_api_v1_tiktok_web_fetch_tag_post_get

        Tag作品/Tag Post  # noqa: E501
        """
        pass

    def test_fetch_tag_post_api_v1_tiktok_web_fetch_tag_post_get_0(self):
        """Test case for fetch_tag_post_api_v1_tiktok_web_fetch_tag_post_get_0

        Tag作品/Tag Post  # noqa: E501
        """
        pass

    def test_fetch_tiktok_live_data_api_v1_tiktok_web_fetch_tiktok_live_data_get(self):
        """Test case for fetch_tiktok_live_data_api_v1_tiktok_web_fetch_tiktok_live_data_get

        通过直播链接获取直播间信息/Get live room information via live link  # noqa: E501
        """
        pass

    def test_fetch_tiktok_live_data_api_v1_tiktok_web_fetch_tiktok_live_data_get_0(self):
        """Test case for fetch_tiktok_live_data_api_v1_tiktok_web_fetch_tiktok_live_data_get_0

        通过直播链接获取直播间信息/Get live room information via live link  # noqa: E501
        """
        pass

    def test_fetch_trending_post_api_v1_tiktok_web_fetch_trending_post_get(self):
        """Test case for fetch_trending_post_api_v1_tiktok_web_fetch_trending_post_get

        获取每日热门内容作品数据/Get daily trending video data  # noqa: E501
        """
        pass

    def test_fetch_trending_post_api_v1_tiktok_web_fetch_trending_post_get_0(self):
        """Test case for fetch_trending_post_api_v1_tiktok_web_fetch_trending_post_get_0

        获取每日热门内容作品数据/Get daily trending video data  # noqa: E501
        """
        pass

    def test_fetch_user_collect_api_v1_tiktok_web_fetch_user_collect_get(self):
        """Test case for fetch_user_collect_api_v1_tiktok_web_fetch_user_collect_get

        获取用户的收藏列表/Get user favorites  # noqa: E501
        """
        pass

    def test_fetch_user_collect_api_v1_tiktok_web_fetch_user_collect_get_0(self):
        """Test case for fetch_user_collect_api_v1_tiktok_web_fetch_user_collect_get_0

        获取用户的收藏列表/Get user favorites  # noqa: E501
        """
        pass

    def test_fetch_user_fans_api_v1_tiktok_web_fetch_user_fans_get(self):
        """Test case for fetch_user_fans_api_v1_tiktok_web_fetch_user_fans_get

        获取用户的粉丝列表/Get user followers  # noqa: E501
        """
        pass

    def test_fetch_user_fans_api_v1_tiktok_web_fetch_user_fans_get_0(self):
        """Test case for fetch_user_fans_api_v1_tiktok_web_fetch_user_fans_get_0

        获取用户的粉丝列表/Get user followers  # noqa: E501
        """
        pass

    def test_fetch_user_follow_api_v1_tiktok_web_fetch_user_follow_get(self):
        """Test case for fetch_user_follow_api_v1_tiktok_web_fetch_user_follow_get

        获取用户的关注列表/Get user followings  # noqa: E501
        """
        pass

    def test_fetch_user_follow_api_v1_tiktok_web_fetch_user_follow_get_0(self):
        """Test case for fetch_user_follow_api_v1_tiktok_web_fetch_user_follow_get_0

        获取用户的关注列表/Get user followings  # noqa: E501
        """
        pass

    def test_fetch_user_like_api_v1_tiktok_web_fetch_user_like_get(self):
        """Test case for fetch_user_like_api_v1_tiktok_web_fetch_user_like_get

        获取用户的点赞列表/Get user likes  # noqa: E501
        """
        pass

    def test_fetch_user_like_api_v1_tiktok_web_fetch_user_like_get_0(self):
        """Test case for fetch_user_like_api_v1_tiktok_web_fetch_user_like_get_0

        获取用户的点赞列表/Get user likes  # noqa: E501
        """
        pass

    def test_fetch_user_mix_api_v1_tiktok_web_fetch_user_mix_get(self):
        """Test case for fetch_user_mix_api_v1_tiktok_web_fetch_user_mix_get

        获取用户的合辑列表/Get user mix list  # noqa: E501
        """
        pass

    def test_fetch_user_mix_api_v1_tiktok_web_fetch_user_mix_get_0(self):
        """Test case for fetch_user_mix_api_v1_tiktok_web_fetch_user_mix_get_0

        获取用户的合辑列表/Get user mix list  # noqa: E501
        """
        pass

    def test_fetch_user_play_list_api_v1_tiktok_web_fetch_user_play_list_get(self):
        """Test case for fetch_user_play_list_api_v1_tiktok_web_fetch_user_play_list_get

        获取用户的播放列表/Get user play list  # noqa: E501
        """
        pass

    def test_fetch_user_play_list_api_v1_tiktok_web_fetch_user_play_list_get_0(self):
        """Test case for fetch_user_play_list_api_v1_tiktok_web_fetch_user_play_list_get_0

        获取用户的播放列表/Get user play list  # noqa: E501
        """
        pass

    def test_fetch_user_post_api_v1_tiktok_web_fetch_user_post_get(self):
        """Test case for fetch_user_post_api_v1_tiktok_web_fetch_user_post_get

        获取用户的作品列表/Get user posts  # noqa: E501
        """
        pass

    def test_fetch_user_post_api_v1_tiktok_web_fetch_user_post_get_0(self):
        """Test case for fetch_user_post_api_v1_tiktok_web_fetch_user_post_get_0

        获取用户的作品列表/Get user posts  # noqa: E501
        """
        pass

    def test_fetch_user_profile_api_v1_tiktok_web_fetch_user_profile_get(self):
        """Test case for fetch_user_profile_api_v1_tiktok_web_fetch_user_profile_get

        获取用户的个人信息/Get user profile  # noqa: E501
        """
        pass

    def test_fetch_user_profile_api_v1_tiktok_web_fetch_user_profile_get_0(self):
        """Test case for fetch_user_profile_api_v1_tiktok_web_fetch_user_profile_get_0

        获取用户的个人信息/Get user profile  # noqa: E501
        """
        pass

    def test_generate_real_ms_token_api_v1_tiktok_web_generate_real_ms_token_get(self):
        """Test case for generate_real_ms_token_api_v1_tiktok_web_generate_real_ms_token_get

        生成真实msToken/Generate real msToken  # noqa: E501
        """
        pass

    def test_generate_real_ms_token_api_v1_tiktok_web_generate_real_ms_token_get_0(self):
        """Test case for generate_real_ms_token_api_v1_tiktok_web_generate_real_ms_token_get_0

        生成真实msToken/Generate real msToken  # noqa: E501
        """
        pass

    def test_generate_ttwid_api_v1_tiktok_web_generate_ttwid_get(self):
        """Test case for generate_ttwid_api_v1_tiktok_web_generate_ttwid_get

        生成ttwid/Generate ttwid  # noqa: E501
        """
        pass

    def test_generate_ttwid_api_v1_tiktok_web_generate_ttwid_get_0(self):
        """Test case for generate_ttwid_api_v1_tiktok_web_generate_ttwid_get_0

        生成ttwid/Generate ttwid  # noqa: E501
        """
        pass

    def test_generate_xbogus_api_v1_tiktok_web_generate_xbogus_post(self):
        """Test case for generate_xbogus_api_v1_tiktok_web_generate_xbogus_post

        生成xbogus/Generate xbogus  # noqa: E501
        """
        pass

    def test_generate_xbogus_api_v1_tiktok_web_generate_xbogus_post_0(self):
        """Test case for generate_xbogus_api_v1_tiktok_web_generate_xbogus_post_0

        生成xbogus/Generate xbogus  # noqa: E501
        """
        pass

    def test_get_all_aweme_id_api_v1_tiktok_web_get_all_aweme_id_post(self):
        """Test case for get_all_aweme_id_api_v1_tiktok_web_get_all_aweme_id_post

        提取列表作品id/Extract list video id  # noqa: E501
        """
        pass

    def test_get_all_aweme_id_api_v1_tiktok_web_get_all_aweme_id_post_0(self):
        """Test case for get_all_aweme_id_api_v1_tiktok_web_get_all_aweme_id_post_0

        提取列表作品id/Extract list video id  # noqa: E501
        """
        pass

    def test_get_all_sec_user_id_api_v1_tiktok_web_get_all_sec_user_id_post(self):
        """Test case for get_all_sec_user_id_api_v1_tiktok_web_get_all_sec_user_id_post

        提取列表用户sec_user_id/Extract list user sec_user_id  # noqa: E501
        """
        pass

    def test_get_all_sec_user_id_api_v1_tiktok_web_get_all_sec_user_id_post_0(self):
        """Test case for get_all_sec_user_id_api_v1_tiktok_web_get_all_sec_user_id_post_0

        提取列表用户sec_user_id/Extract list user sec_user_id  # noqa: E501
        """
        pass

    def test_get_all_unique_id_api_v1_tiktok_web_get_all_unique_id_post(self):
        """Test case for get_all_unique_id_api_v1_tiktok_web_get_all_unique_id_post

        获取列表unique_id/Get list unique_id  # noqa: E501
        """
        pass

    def test_get_all_unique_id_api_v1_tiktok_web_get_all_unique_id_post_0(self):
        """Test case for get_all_unique_id_api_v1_tiktok_web_get_all_unique_id_post_0

        获取列表unique_id/Get list unique_id  # noqa: E501
        """
        pass

    def test_get_aweme_id_api_v1_tiktok_web_get_aweme_id_get(self):
        """Test case for get_aweme_id_api_v1_tiktok_web_get_aweme_id_get

        提取单个作品id/Extract single video id  # noqa: E501
        """
        pass

    def test_get_aweme_id_api_v1_tiktok_web_get_aweme_id_get_0(self):
        """Test case for get_aweme_id_api_v1_tiktok_web_get_aweme_id_get_0

        提取单个作品id/Extract single video id  # noqa: E501
        """
        pass

    def test_get_live_room_id_api_v1_tiktok_web_get_live_room_id_get(self):
        """Test case for get_live_room_id_api_v1_tiktok_web_get_live_room_id_get

        根据直播间链接提取直播间ID/Extract live room ID from live room link  # noqa: E501
        """
        pass

    def test_get_live_room_id_api_v1_tiktok_web_get_live_room_id_get_0(self):
        """Test case for get_live_room_id_api_v1_tiktok_web_get_live_room_id_get_0

        根据直播间链接提取直播间ID/Extract live room ID from live room link  # noqa: E501
        """
        pass

    def test_get_sec_user_id_api_v1_tiktok_web_get_sec_user_id_get(self):
        """Test case for get_sec_user_id_api_v1_tiktok_web_get_sec_user_id_get

        提取用户sec_user_id/Extract user sec_user_id  # noqa: E501
        """
        pass

    def test_get_sec_user_id_api_v1_tiktok_web_get_sec_user_id_get_0(self):
        """Test case for get_sec_user_id_api_v1_tiktok_web_get_sec_user_id_get_0

        提取用户sec_user_id/Extract user sec_user_id  # noqa: E501
        """
        pass

    def test_get_unique_id_api_v1_tiktok_web_get_unique_id_get(self):
        """Test case for get_unique_id_api_v1_tiktok_web_get_unique_id_get

        获取用户unique_id/Get user unique_id  # noqa: E501
        """
        pass

    def test_get_unique_id_api_v1_tiktok_web_get_unique_id_get_0(self):
        """Test case for get_unique_id_api_v1_tiktok_web_get_unique_id_get_0

        获取用户unique_id/Get user unique_id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
