# coding: utf-8

"""
    TikHub.io - Your Ultimate Social Media Data & API Marketplace

    High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import tikhub_sdk_v2
from tikhub_sdk_v2.api.we_chat_media_platform_web_api_api import WeChatMediaPlatformWebAPIApi  # noqa: E501
from tikhub_sdk_v2.rest import ApiException


class TestWeChatMediaPlatformWebAPIApi(unittest.TestCase):
    """WeChatMediaPlatformWebAPIApi unit test stubs"""

    def setUp(self):
        self.api = tikhub_sdk_v2.api.we_chat_media_platform_web_api_api.WeChatMediaPlatformWebAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch_mp_article_ad_api_v1_wechat_mp_web_fetch_mp_article_ad_get(self):
        """Test case for fetch_mp_article_ad_api_v1_wechat_mp_web_fetch_mp_article_ad_get

        获取微信公众号广告/Get Wechat MP Article Ad  # noqa: E501
        """
        pass

    def test_fetch_mp_article_ad_api_v1_wechat_mp_web_fetch_mp_article_ad_get_0(self):
        """Test case for fetch_mp_article_ad_api_v1_wechat_mp_web_fetch_mp_article_ad_get_0

        获取微信公众号广告/Get Wechat MP Article Ad  # noqa: E501
        """
        pass

    def test_fetch_mp_article_comment_list_api_v1_wechat_mp_web_fetch_mp_article_comment_list_get(self):
        """Test case for fetch_mp_article_comment_list_api_v1_wechat_mp_web_fetch_mp_article_comment_list_get

        获取微信公众号文章评论列表/Get Wechat MP Article Comment List  # noqa: E501
        """
        pass

    def test_fetch_mp_article_comment_list_api_v1_wechat_mp_web_fetch_mp_article_comment_list_get_0(self):
        """Test case for fetch_mp_article_comment_list_api_v1_wechat_mp_web_fetch_mp_article_comment_list_get_0

        获取微信公众号文章评论列表/Get Wechat MP Article Comment List  # noqa: E501
        """
        pass

    def test_fetch_mp_article_comment_reply_list_api_v1_wechat_mp_web_fetch_mp_article_comment_reply_list_get(self):
        """Test case for fetch_mp_article_comment_reply_list_api_v1_wechat_mp_web_fetch_mp_article_comment_reply_list_get

        获取微信公众号文章评论回复列表/Get Wechat MP Article Comment Reply List  # noqa: E501
        """
        pass

    def test_fetch_mp_article_comment_reply_list_api_v1_wechat_mp_web_fetch_mp_article_comment_reply_list_get_0(self):
        """Test case for fetch_mp_article_comment_reply_list_api_v1_wechat_mp_web_fetch_mp_article_comment_reply_list_get_0

        获取微信公众号文章评论回复列表/Get Wechat MP Article Comment Reply List  # noqa: E501
        """
        pass

    def test_fetch_mp_article_detail_html_api_v1_wechat_mp_web_fetch_mp_article_detail_html_get(self):
        """Test case for fetch_mp_article_detail_html_api_v1_wechat_mp_web_fetch_mp_article_detail_html_get

        获取微信公众号文章详情的HTML/Get Wechat MP Article Detail HTML  # noqa: E501
        """
        pass

    def test_fetch_mp_article_detail_html_api_v1_wechat_mp_web_fetch_mp_article_detail_html_get_0(self):
        """Test case for fetch_mp_article_detail_html_api_v1_wechat_mp_web_fetch_mp_article_detail_html_get_0

        获取微信公众号文章详情的HTML/Get Wechat MP Article Detail HTML  # noqa: E501
        """
        pass

    def test_fetch_mp_article_detail_json_api_v1_wechat_mp_web_fetch_mp_article_detail_json_get(self):
        """Test case for fetch_mp_article_detail_json_api_v1_wechat_mp_web_fetch_mp_article_detail_json_get

        获取微信公众号文章详情的JSON/Get Wechat MP Article Detail JSON  # noqa: E501
        """
        pass

    def test_fetch_mp_article_detail_json_api_v1_wechat_mp_web_fetch_mp_article_detail_json_get_0(self):
        """Test case for fetch_mp_article_detail_json_api_v1_wechat_mp_web_fetch_mp_article_detail_json_get_0

        获取微信公众号文章详情的JSON/Get Wechat MP Article Detail JSON  # noqa: E501
        """
        pass

    def test_fetch_mp_article_list_api_v1_wechat_mp_web_fetch_mp_article_list_get(self):
        """Test case for fetch_mp_article_list_api_v1_wechat_mp_web_fetch_mp_article_list_get

        获取微信公众号文章列表/Get Wechat MP Article List  # noqa: E501
        """
        pass

    def test_fetch_mp_article_list_api_v1_wechat_mp_web_fetch_mp_article_list_get_0(self):
        """Test case for fetch_mp_article_list_api_v1_wechat_mp_web_fetch_mp_article_list_get_0

        获取微信公众号文章列表/Get Wechat MP Article List  # noqa: E501
        """
        pass

    def test_fetch_mp_article_read_count_api_v1_wechat_mp_web_fetch_mp_article_read_count_get(self):
        """Test case for fetch_mp_article_read_count_api_v1_wechat_mp_web_fetch_mp_article_read_count_get

        获取微信公众号文章阅读量/Get Wechat MP Article Read Count  # noqa: E501
        """
        pass

    def test_fetch_mp_article_read_count_api_v1_wechat_mp_web_fetch_mp_article_read_count_get_0(self):
        """Test case for fetch_mp_article_read_count_api_v1_wechat_mp_web_fetch_mp_article_read_count_get_0

        获取微信公众号文章阅读量/Get Wechat MP Article Read Count  # noqa: E501
        """
        pass

    def test_fetch_mp_article_url_api_v1_wechat_mp_web_fetch_mp_article_url_get(self):
        """Test case for fetch_mp_article_url_api_v1_wechat_mp_web_fetch_mp_article_url_get

        获取微信公众号文章永久链接/Get Wechat MP Article URL  # noqa: E501
        """
        pass

    def test_fetch_mp_article_url_api_v1_wechat_mp_web_fetch_mp_article_url_get_0(self):
        """Test case for fetch_mp_article_url_api_v1_wechat_mp_web_fetch_mp_article_url_get_0

        获取微信公众号文章永久链接/Get Wechat MP Article URL  # noqa: E501
        """
        pass

    def test_fetch_mp_article_url_conversion_api_v1_wechat_mp_web_fetch_mp_article_url_conversion_get(self):
        """Test case for fetch_mp_article_url_conversion_api_v1_wechat_mp_web_fetch_mp_article_url_conversion_get

        获取微信公众号长链接转短链接/Get Wechat MP Long URL to Short URL  # noqa: E501
        """
        pass

    def test_fetch_mp_article_url_conversion_api_v1_wechat_mp_web_fetch_mp_article_url_conversion_get_0(self):
        """Test case for fetch_mp_article_url_conversion_api_v1_wechat_mp_web_fetch_mp_article_url_conversion_get_0

        获取微信公众号长链接转短链接/Get Wechat MP Long URL to Short URL  # noqa: E501
        """
        pass

    def test_fetch_mp_related_articles_api_v1_wechat_mp_web_fetch_mp_related_articles_get(self):
        """Test case for fetch_mp_related_articles_api_v1_wechat_mp_web_fetch_mp_related_articles_get

        获取微信公众号关联文章/Get Wechat MP Related Articles  # noqa: E501
        """
        pass

    def test_fetch_mp_related_articles_api_v1_wechat_mp_web_fetch_mp_related_articles_get_0(self):
        """Test case for fetch_mp_related_articles_api_v1_wechat_mp_web_fetch_mp_related_articles_get_0

        获取微信公众号关联文章/Get Wechat MP Related Articles  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
