# coding: utf-8

"""
    TikHub.io - Your Ultimate Social Media Data & API Marketplace

    High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import tikhub_sdk_v2
from tikhub_sdk_v2.api.tik_hub_user_api_api import TikHubUserAPIApi  # noqa: E501
from tikhub_sdk_v2.rest import ApiException


class TestTikHubUserAPIApi(unittest.TestCase):
    """TikHubUserAPIApi unit test stubs"""

    def setUp(self):
        self.api = tikhub_sdk_v2.api.tik_hub_user_api_api.TikHubUserAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_calculate_price_api_v1_tikhub_user_calculate_price_get(self):
        """Test case for calculate_price_api_v1_tikhub_user_calculate_price_get

        计算价格/Calculate price  # noqa: E501
        """
        pass

    def test_calculate_price_api_v1_tikhub_user_calculate_price_get_0(self):
        """Test case for calculate_price_api_v1_tikhub_user_calculate_price_get_0

        计算价格/Calculate price  # noqa: E501
        """
        pass

    def test_get_all_endpoints_info_api_v1_tikhub_user_get_all_endpoints_info_get(self):
        """Test case for get_all_endpoints_info_api_v1_tikhub_user_get_all_endpoints_info_get

        获取所有端点信息/Get all endpoints information  # noqa: E501
        """
        pass

    def test_get_all_endpoints_info_api_v1_tikhub_user_get_all_endpoints_info_get_0(self):
        """Test case for get_all_endpoints_info_api_v1_tikhub_user_get_all_endpoints_info_get_0

        获取所有端点信息/Get all endpoints information  # noqa: E501
        """
        pass

    def test_get_endpoint_info_api_v1_tikhub_user_get_endpoint_info_get(self):
        """Test case for get_endpoint_info_api_v1_tikhub_user_get_endpoint_info_get

        获取一个端点的信息/Get information of an endpoint  # noqa: E501
        """
        pass

    def test_get_endpoint_info_api_v1_tikhub_user_get_endpoint_info_get_0(self):
        """Test case for get_endpoint_info_api_v1_tikhub_user_get_endpoint_info_get_0

        获取一个端点的信息/Get information of an endpoint  # noqa: E501
        """
        pass

    def test_get_tiered_discount_info_api_v1_tikhub_user_get_tiered_discount_info_get(self):
        """Test case for get_tiered_discount_info_api_v1_tikhub_user_get_tiered_discount_info_get

        获取阶梯式折扣百分比信息/Get tiered discount percentage information  # noqa: E501
        """
        pass

    def test_get_tiered_discount_info_api_v1_tikhub_user_get_tiered_discount_info_get_0(self):
        """Test case for get_tiered_discount_info_api_v1_tikhub_user_get_tiered_discount_info_get_0

        获取阶梯式折扣百分比信息/Get tiered discount percentage information  # noqa: E501
        """
        pass

    def test_get_user_daily_usage_api_v1_tikhub_user_get_user_daily_usage_get(self):
        """Test case for get_user_daily_usage_api_v1_tikhub_user_get_user_daily_usage_get

        获取用户每日使用情况/Get user daily usage  # noqa: E501
        """
        pass

    def test_get_user_daily_usage_api_v1_tikhub_user_get_user_daily_usage_get_0(self):
        """Test case for get_user_daily_usage_api_v1_tikhub_user_get_user_daily_usage_get_0

        获取用户每日使用情况/Get user daily usage  # noqa: E501
        """
        pass

    def test_get_user_info_api_v1_tikhub_user_get_user_info_get(self):
        """Test case for get_user_info_api_v1_tikhub_user_get_user_info_get

        获取TikHub用户信息/Get TikHub user info  # noqa: E501
        """
        pass

    def test_get_user_info_api_v1_tikhub_user_get_user_info_get_0(self):
        """Test case for get_user_info_api_v1_tikhub_user_get_user_info_get_0

        获取TikHub用户信息/Get TikHub user info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
