# coding: utf-8

"""
    TikHub.io - Your Ultimate Social Media Data & API Marketplace

    High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import tikhub_sdk_v2
from tikhub_sdk_v2.api.lemon8_app_api_api import Lemon8AppAPIApi  # noqa: E501
from tikhub_sdk_v2.rest import ApiException


class TestLemon8AppAPIApi(unittest.TestCase):
    """Lemon8AppAPIApi unit test stubs"""

    def setUp(self):
        self.api = tikhub_sdk_v2.api.lemon8_app_api_api.Lemon8AppAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch_discover_banners_api_v1_lemon8_app_fetch_discover_banners_get(self):
        """Test case for fetch_discover_banners_api_v1_lemon8_app_fetch_discover_banners_get

        获取发现页Banner/Get banners of discover page  # noqa: E501
        """
        pass

    def test_fetch_discover_banners_api_v1_lemon8_app_fetch_discover_banners_get_0(self):
        """Test case for fetch_discover_banners_api_v1_lemon8_app_fetch_discover_banners_get_0

        获取发现页Banner/Get banners of discover page  # noqa: E501
        """
        pass

    def test_fetch_discover_tab_api_v1_lemon8_app_fetch_discover_tab_get(self):
        """Test case for fetch_discover_tab_api_v1_lemon8_app_fetch_discover_tab_get

        获取发现页主体内容/Get main content of discover page  # noqa: E501
        """
        pass

    def test_fetch_discover_tab_api_v1_lemon8_app_fetch_discover_tab_get_0(self):
        """Test case for fetch_discover_tab_api_v1_lemon8_app_fetch_discover_tab_get_0

        获取发现页主体内容/Get main content of discover page  # noqa: E501
        """
        pass

    def test_fetch_discover_tab_information_tabs_api_v1_lemon8_app_fetch_discover_tab_information_tabs_get(self):
        """Test case for fetch_discover_tab_information_tabs_api_v1_lemon8_app_fetch_discover_tab_information_tabs_get

        获取发现页的 Editor's Picks/Get Editor's Picks of discover page  # noqa: E501
        """
        pass

    def test_fetch_discover_tab_information_tabs_api_v1_lemon8_app_fetch_discover_tab_information_tabs_get_0(self):
        """Test case for fetch_discover_tab_information_tabs_api_v1_lemon8_app_fetch_discover_tab_information_tabs_get_0

        获取发现页的 Editor's Picks/Get Editor's Picks of discover page  # noqa: E501
        """
        pass

    def test_fetch_hot_search_keywords_api_v1_lemon8_app_fetch_hot_search_keywords_get(self):
        """Test case for fetch_hot_search_keywords_api_v1_lemon8_app_fetch_hot_search_keywords_get

        获取热搜关键词/Get hot search keywords  # noqa: E501
        """
        pass

    def test_fetch_hot_search_keywords_api_v1_lemon8_app_fetch_hot_search_keywords_get_0(self):
        """Test case for fetch_hot_search_keywords_api_v1_lemon8_app_fetch_hot_search_keywords_get_0

        获取热搜关键词/Get hot search keywords  # noqa: E501
        """
        pass

    def test_fetch_post_comment_list_api_v1_lemon8_app_fetch_post_comment_list_get(self):
        """Test case for fetch_post_comment_list_api_v1_lemon8_app_fetch_post_comment_list_get

        获取指定作品的评论列表/Get comments list of specified post  # noqa: E501
        """
        pass

    def test_fetch_post_comment_list_api_v1_lemon8_app_fetch_post_comment_list_get_0(self):
        """Test case for fetch_post_comment_list_api_v1_lemon8_app_fetch_post_comment_list_get_0

        获取指定作品的评论列表/Get comments list of specified post  # noqa: E501
        """
        pass

    def test_fetch_post_detail_api_v1_lemon8_app_fetch_post_detail_get(self):
        """Test case for fetch_post_detail_api_v1_lemon8_app_fetch_post_detail_get

        获取指定作品的信息/Get information of specified post  # noqa: E501
        """
        pass

    def test_fetch_post_detail_api_v1_lemon8_app_fetch_post_detail_get_0(self):
        """Test case for fetch_post_detail_api_v1_lemon8_app_fetch_post_detail_get_0

        获取指定作品的信息/Get information of specified post  # noqa: E501
        """
        pass

    def test_fetch_search_api_v1_lemon8_app_fetch_search_get(self):
        """Test case for fetch_search_api_v1_lemon8_app_fetch_search_get

        搜索接口/Search API  # noqa: E501
        """
        pass

    def test_fetch_search_api_v1_lemon8_app_fetch_search_get_0(self):
        """Test case for fetch_search_api_v1_lemon8_app_fetch_search_get_0

        搜索接口/Search API  # noqa: E501
        """
        pass

    def test_fetch_topic_info_api_v1_lemon8_app_fetch_topic_info_get(self):
        """Test case for fetch_topic_info_api_v1_lemon8_app_fetch_topic_info_get

        获取话题信息/Get topic information  # noqa: E501
        """
        pass

    def test_fetch_topic_info_api_v1_lemon8_app_fetch_topic_info_get_0(self):
        """Test case for fetch_topic_info_api_v1_lemon8_app_fetch_topic_info_get_0

        获取话题信息/Get topic information  # noqa: E501
        """
        pass

    def test_fetch_topic_post_list_api_v1_lemon8_app_fetch_topic_post_list_get(self):
        """Test case for fetch_topic_post_list_api_v1_lemon8_app_fetch_topic_post_list_get

        获取话题作品列表/Get topic post list  # noqa: E501
        """
        pass

    def test_fetch_topic_post_list_api_v1_lemon8_app_fetch_topic_post_list_get_0(self):
        """Test case for fetch_topic_post_list_api_v1_lemon8_app_fetch_topic_post_list_get_0

        获取话题作品列表/Get topic post list  # noqa: E501
        """
        pass

    def test_fetch_user_follower_list_api_v1_lemon8_app_fetch_user_follower_list_get(self):
        """Test case for fetch_user_follower_list_api_v1_lemon8_app_fetch_user_follower_list_get

        获取指定用户的粉丝列表/Get fans list of specified user  # noqa: E501
        """
        pass

    def test_fetch_user_follower_list_api_v1_lemon8_app_fetch_user_follower_list_get_0(self):
        """Test case for fetch_user_follower_list_api_v1_lemon8_app_fetch_user_follower_list_get_0

        获取指定用户的粉丝列表/Get fans list of specified user  # noqa: E501
        """
        pass

    def test_fetch_user_following_list_api_v1_lemon8_app_fetch_user_following_list_get(self):
        """Test case for fetch_user_following_list_api_v1_lemon8_app_fetch_user_following_list_get

        获取指定用户的关注列表/Get following list of specified user  # noqa: E501
        """
        pass

    def test_fetch_user_following_list_api_v1_lemon8_app_fetch_user_following_list_get_0(self):
        """Test case for fetch_user_following_list_api_v1_lemon8_app_fetch_user_following_list_get_0

        获取指定用户的关注列表/Get following list of specified user  # noqa: E501
        """
        pass

    def test_get_item_id_api_v1_lemon8_app_get_item_id_get(self):
        """Test case for get_item_id_api_v1_lemon8_app_get_item_id_get

        通过分享链接获取作品ID/Get post ID through sharing link  # noqa: E501
        """
        pass

    def test_get_item_id_api_v1_lemon8_app_get_item_id_get_0(self):
        """Test case for get_item_id_api_v1_lemon8_app_get_item_id_get_0

        通过分享链接获取作品ID/Get post ID through sharing link  # noqa: E501
        """
        pass

    def test_get_item_ids_api_v1_lemon8_app_get_item_ids_post(self):
        """Test case for get_item_ids_api_v1_lemon8_app_get_item_ids_post

        通过分享链接批量获取作品ID/Get post IDs in batch through sharing links  # noqa: E501
        """
        pass

    def test_get_item_ids_api_v1_lemon8_app_get_item_ids_post_0(self):
        """Test case for get_item_ids_api_v1_lemon8_app_get_item_ids_post_0

        通过分享链接批量获取作品ID/Get post IDs in batch through sharing links  # noqa: E501
        """
        pass

    def test_get_user_id_api_v1_lemon8_app_get_user_id_get(self):
        """Test case for get_user_id_api_v1_lemon8_app_get_user_id_get

        通过分享链接获取用户ID/Get user ID through sharing link  # noqa: E501
        """
        pass

    def test_get_user_id_api_v1_lemon8_app_get_user_id_get_0(self):
        """Test case for get_user_id_api_v1_lemon8_app_get_user_id_get_0

        通过分享链接获取用户ID/Get user ID through sharing link  # noqa: E501
        """
        pass

    def test_get_user_ids_api_v1_lemon8_app_get_user_ids_post(self):
        """Test case for get_user_ids_api_v1_lemon8_app_get_user_ids_post

        通过分享链接批量获取用户ID/Get user IDs in batch through sharing links  # noqa: E501
        """
        pass

    def test_get_user_ids_api_v1_lemon8_app_get_user_ids_post_0(self):
        """Test case for get_user_ids_api_v1_lemon8_app_get_user_ids_post_0

        通过分享链接批量获取用户ID/Get user IDs in batch through sharing links  # noqa: E501
        """
        pass

    def test_handler_user_profile_api_v1_lemon8_app_fetch_user_profile_get(self):
        """Test case for handler_user_profile_api_v1_lemon8_app_fetch_user_profile_get

        获取指定用户的信息/Get information of specified user  # noqa: E501
        """
        pass

    def test_handler_user_profile_api_v1_lemon8_app_fetch_user_profile_get_0(self):
        """Test case for handler_user_profile_api_v1_lemon8_app_fetch_user_profile_get_0

        获取指定用户的信息/Get information of specified user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
