# coding: utf-8

"""
    TikHub.io - Your Ultimate Social Media Data & API Marketplace

    High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import tikhub_sdk_v2
from tikhub_sdk_v2.api.net_ease_cloud_music_api_api import NetEaseCloudMusicAPIApi  # noqa: E501
from tikhub_sdk_v2.rest import ApiException


class TestNetEaseCloudMusicAPIApi(unittest.TestCase):
    """NetEaseCloudMusicAPIApi unit test stubs"""

    def setUp(self):
        self.api = tikhub_sdk_v2.api.net_ease_cloud_music_api_api.NetEaseCloudMusicAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_decrypt_post_payload_api_v1_net_ease_cloud_music_app_decrypt_post_payload_post(self):
        """Test case for decrypt_post_payload_api_v1_net_ease_cloud_music_app_decrypt_post_payload_post

        解密POST请求中的16进制payload/Decrypt the 16-bit payload in the POST request  # noqa: E501
        """
        pass

    def test_decrypt_post_payload_api_v1_net_ease_cloud_music_app_decrypt_post_payload_post_0(self):
        """Test case for decrypt_post_payload_api_v1_net_ease_cloud_music_app_decrypt_post_payload_post_0

        解密POST请求中的16进制payload/Decrypt the 16-bit payload in the POST request  # noqa: E501
        """
        pass

    def test_encrypt_post_payload_api_v1_net_ease_cloud_music_app_encrypt_post_payload_post(self):
        """Test case for encrypt_post_payload_api_v1_net_ease_cloud_music_app_encrypt_post_payload_post

        加密POST请求中的payload并且返回16进制/Encrypt the payload in the POST request and return 16 hexadecimal  # noqa: E501
        """
        pass

    def test_encrypt_post_payload_api_v1_net_ease_cloud_music_app_encrypt_post_payload_post_0(self):
        """Test case for encrypt_post_payload_api_v1_net_ease_cloud_music_app_encrypt_post_payload_post_0

        加密POST请求中的payload并且返回16进制/Encrypt the payload in the POST request and return 16 hexadecimal  # noqa: E501
        """
        pass

    def test_fetch_artist_detail_api_v1_net_ease_cloud_music_app_fetch_artist_detail_get(self):
        """Test case for fetch_artist_detail_api_v1_net_ease_cloud_music_app_fetch_artist_detail_get

        获取歌手信息/Fetch artist detail  # noqa: E501
        """
        pass

    def test_fetch_artist_detail_api_v1_net_ease_cloud_music_app_fetch_artist_detail_get_0(self):
        """Test case for fetch_artist_detail_api_v1_net_ease_cloud_music_app_fetch_artist_detail_get_0

        获取歌手信息/Fetch artist detail  # noqa: E501
        """
        pass

    def test_fetch_music_comment_api_v1_net_ease_cloud_music_app_fetch_music_comment_get(self):
        """Test case for fetch_music_comment_api_v1_net_ease_cloud_music_app_fetch_music_comment_get

        获取歌曲评论/Fetch music comment  # noqa: E501
        """
        pass

    def test_fetch_music_comment_api_v1_net_ease_cloud_music_app_fetch_music_comment_get_0(self):
        """Test case for fetch_music_comment_api_v1_net_ease_cloud_music_app_fetch_music_comment_get_0

        获取歌曲评论/Fetch music comment  # noqa: E501
        """
        pass

    def test_fetch_music_log_video_url_api_v1_net_ease_cloud_music_app_fetch_music_log_video_url_get(self):
        """Test case for fetch_music_log_video_url_api_v1_net_ease_cloud_music_app_fetch_music_log_video_url_get

        Mlog（音乐视频）播放地址/Mlog (music video) playback address  # noqa: E501
        """
        pass

    def test_fetch_music_log_video_url_api_v1_net_ease_cloud_music_app_fetch_music_log_video_url_get_0(self):
        """Test case for fetch_music_log_video_url_api_v1_net_ease_cloud_music_app_fetch_music_log_video_url_get_0

        Mlog（音乐视频）播放地址/Mlog (music video) playback address  # noqa: E501
        """
        pass

    def test_fetch_one_music_lyric_api_v1_net_ease_cloud_music_app_fetch_one_music_lyric_get(self):
        """Test case for fetch_one_music_lyric_api_v1_net_ease_cloud_music_app_fetch_one_music_lyric_get

        获取单一歌曲歌词/Fetch one music lyric  # noqa: E501
        """
        pass

    def test_fetch_one_music_lyric_api_v1_net_ease_cloud_music_app_fetch_one_music_lyric_get_0(self):
        """Test case for fetch_one_music_lyric_api_v1_net_ease_cloud_music_app_fetch_one_music_lyric_get_0

        获取单一歌曲歌词/Fetch one music lyric  # noqa: E501
        """
        pass

    def test_fetch_one_music_url_v1_api_v1_net_ease_cloud_music_app_fetch_one_music_url_v1_get(self):
        """Test case for fetch_one_music_url_v1_api_v1_net_ease_cloud_music_app_fetch_one_music_url_v1_get

        获取单一歌曲播放地址V1（只能返回MP3格式，支持参数较少）/Fetch one music URL V1 (only MP3 format is supported, with fewer parameters)  # noqa: E501
        """
        pass

    def test_fetch_one_music_url_v1_api_v1_net_ease_cloud_music_app_fetch_one_music_url_v1_get_0(self):
        """Test case for fetch_one_music_url_v1_api_v1_net_ease_cloud_music_app_fetch_one_music_url_v1_get_0

        获取单一歌曲播放地址V1（只能返回MP3格式，支持参数较少）/Fetch one music URL V1 (only MP3 format is supported, with fewer parameters)  # noqa: E501
        """
        pass

    def test_fetch_one_music_url_v2_api_v1_net_ease_cloud_music_app_fetch_one_music_url_v2_get(self):
        """Test case for fetch_one_music_url_v2_api_v1_net_ease_cloud_music_app_fetch_one_music_url_v2_get

        获取单一歌曲播放地址V2（支持更多参数）/Fetch one music URL V2 (support more parameters)  # noqa: E501
        """
        pass

    def test_fetch_one_music_url_v2_api_v1_net_ease_cloud_music_app_fetch_one_music_url_v2_get_0(self):
        """Test case for fetch_one_music_url_v2_api_v1_net_ease_cloud_music_app_fetch_one_music_url_v2_get_0

        获取单一歌曲播放地址V2（支持更多参数）/Fetch one music URL V2 (support more parameters)  # noqa: E501
        """
        pass

    def test_fetch_one_music_v1_api_v1_net_ease_cloud_music_app_fetch_one_music_v1_get(self):
        """Test case for fetch_one_music_v1_api_v1_net_ease_cloud_music_app_fetch_one_music_v1_get

        获取单一歌曲信息V1（信息更全）| Fetch one music information V1 (more information)  # noqa: E501
        """
        pass

    def test_fetch_one_music_v1_api_v1_net_ease_cloud_music_app_fetch_one_music_v1_get_0(self):
        """Test case for fetch_one_music_v1_api_v1_net_ease_cloud_music_app_fetch_one_music_v1_get_0

        获取单一歌曲信息V1（信息更全）| Fetch one music information V1 (more information)  # noqa: E501
        """
        pass

    def test_fetch_one_music_v2_api_v1_net_ease_cloud_music_app_fetch_one_music_v2_get(self):
        """Test case for fetch_one_music_v2_api_v1_net_ease_cloud_music_app_fetch_one_music_v2_get

        获取单一歌曲信息V2（信息更少）| Fetch one music information V2 (less information)  # noqa: E501
        """
        pass

    def test_fetch_one_music_v2_api_v1_net_ease_cloud_music_app_fetch_one_music_v2_get_0(self):
        """Test case for fetch_one_music_v2_api_v1_net_ease_cloud_music_app_fetch_one_music_v2_get_0

        获取单一歌曲信息V2（信息更少）| Fetch one music information V2 (less information)  # noqa: E501
        """
        pass

    def test_fetch_user_event_api_v1_net_ease_cloud_music_app_fetch_user_event_get(self):
        """Test case for fetch_user_event_api_v1_net_ease_cloud_music_app_fetch_user_event_get

        获取用户动态/Fetch user event  # noqa: E501
        """
        pass

    def test_fetch_user_event_api_v1_net_ease_cloud_music_app_fetch_user_event_get_0(self):
        """Test case for fetch_user_event_api_v1_net_ease_cloud_music_app_fetch_user_event_get_0

        获取用户动态/Fetch user event  # noqa: E501
        """
        pass

    def test_fetch_user_followers_api_v1_net_ease_cloud_music_app_fetch_user_followers_get(self):
        """Test case for fetch_user_followers_api_v1_net_ease_cloud_music_app_fetch_user_followers_get

        获取用户粉丝列表/Fetch user followers  # noqa: E501
        """
        pass

    def test_fetch_user_followers_api_v1_net_ease_cloud_music_app_fetch_user_followers_get_0(self):
        """Test case for fetch_user_followers_api_v1_net_ease_cloud_music_app_fetch_user_followers_get_0

        获取用户粉丝列表/Fetch user followers  # noqa: E501
        """
        pass

    def test_fetch_user_follows_api_v1_net_ease_cloud_music_app_fetch_user_follows_get(self):
        """Test case for fetch_user_follows_api_v1_net_ease_cloud_music_app_fetch_user_follows_get

        获取用户关注列表/Fetch user follows  # noqa: E501
        """
        pass

    def test_fetch_user_follows_api_v1_net_ease_cloud_music_app_fetch_user_follows_get_0(self):
        """Test case for fetch_user_follows_api_v1_net_ease_cloud_music_app_fetch_user_follows_get_0

        获取用户关注列表/Fetch user follows  # noqa: E501
        """
        pass

    def test_fetch_user_info_api_v1_net_ease_cloud_music_app_fetch_user_info_get(self):
        """Test case for fetch_user_info_api_v1_net_ease_cloud_music_app_fetch_user_info_get

        获取用户信息/Get user information  # noqa: E501
        """
        pass

    def test_fetch_user_info_api_v1_net_ease_cloud_music_app_fetch_user_info_get_0(self):
        """Test case for fetch_user_info_api_v1_net_ease_cloud_music_app_fetch_user_info_get_0

        获取用户信息/Get user information  # noqa: E501
        """
        pass

    def test_fetch_user_playlist_api_v1_net_ease_cloud_music_app_fetch_user_playlist_get(self):
        """Test case for fetch_user_playlist_api_v1_net_ease_cloud_music_app_fetch_user_playlist_get

        获取用户歌单/Get user playlist  # noqa: E501
        """
        pass

    def test_fetch_user_playlist_api_v1_net_ease_cloud_music_app_fetch_user_playlist_get_0(self):
        """Test case for fetch_user_playlist_api_v1_net_ease_cloud_music_app_fetch_user_playlist_get_0

        获取用户歌单/Get user playlist  # noqa: E501
        """
        pass

    def test_search_v1_api_v1_net_ease_cloud_music_app_search_v1_get(self):
        """Test case for search_v1_api_v1_net_ease_cloud_music_app_search_v1_get

        搜索接口V1/Search interface V1  # noqa: E501
        """
        pass

    def test_search_v1_api_v1_net_ease_cloud_music_app_search_v1_get_0(self):
        """Test case for search_v1_api_v1_net_ease_cloud_music_app_search_v1_get_0

        搜索接口V1/Search interface V1  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
