# coding: utf-8

"""
    TikHub.io - Your Ultimate Social Media Data & API Marketplace

    High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import tikhub_sdk_v2
from tikhub_sdk_v2.api.kuaishou_web_api_api import KuaishouWebAPIApi  # noqa: E501
from tikhub_sdk_v2.rest import ApiException


class TestKuaishouWebAPIApi(unittest.TestCase):
    """KuaishouWebAPIApi unit test stubs"""

    def setUp(self):
        self.api = tikhub_sdk_v2.api.kuaishou_web_api_api.KuaishouWebAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch_home_page_info_api_v1_kuaishou_web_fetch_home_page_info_get(self):
        """Test case for fetch_home_page_info_api_v1_kuaishou_web_fetch_home_page_info_get

        获取主页信息数据/Get home page info data  # noqa: E501
        """
        pass

    def test_fetch_home_page_info_api_v1_kuaishou_web_fetch_home_page_info_get_0(self):
        """Test case for fetch_home_page_info_api_v1_kuaishou_web_fetch_home_page_info_get_0

        获取主页信息数据/Get home page info data  # noqa: E501
        """
        pass

    def test_fetch_home_page_video_api_v1_kuaishou_web_fetch_home_page_video_get(self):
        """Test case for fetch_home_page_video_api_v1_kuaishou_web_fetch_home_page_video_get

        获取主页视频数据/Get home page video data  # noqa: E501
        """
        pass

    def test_fetch_home_page_video_api_v1_kuaishou_web_fetch_home_page_video_get_0(self):
        """Test case for fetch_home_page_video_api_v1_kuaishou_web_fetch_home_page_video_get_0

        获取主页视频数据/Get home page video data  # noqa: E501
        """
        pass

    def test_fetch_one_video_api_v1_kuaishou_web_fetch_one_video_get(self):
        """Test case for fetch_one_video_api_v1_kuaishou_web_fetch_one_video_get

        获取单个作品数据/Get single video data  # noqa: E501
        """
        pass

    def test_fetch_one_video_api_v1_kuaishou_web_fetch_one_video_get_0(self):
        """Test case for fetch_one_video_api_v1_kuaishou_web_fetch_one_video_get_0

        获取单个作品数据/Get single video data  # noqa: E501
        """
        pass

    def test_fetch_one_video_by_url_api_v1_kuaishou_web_fetch_one_video_by_url_get(self):
        """Test case for fetch_one_video_by_url_api_v1_kuaishou_web_fetch_one_video_by_url_get

        根据链接获取单个作品数据/Fetch single video by URL  # noqa: E501
        """
        pass

    def test_fetch_one_video_by_url_api_v1_kuaishou_web_fetch_one_video_by_url_get_0(self):
        """Test case for fetch_one_video_by_url_api_v1_kuaishou_web_fetch_one_video_by_url_get_0

        根据链接获取单个作品数据/Fetch single video by URL  # noqa: E501
        """
        pass

    def test_fetch_one_video_by_url_v2_api_v1_kuaishou_web_fetch_one_video_by_url_v2_get(self):
        """Test case for fetch_one_video_by_url_v2_api_v1_kuaishou_web_fetch_one_video_by_url_v2_get

        根据链接获取单个作品数据V2/Fetch single video by URL V2  # noqa: E501
        """
        pass

    def test_fetch_one_video_by_url_v2_api_v1_kuaishou_web_fetch_one_video_by_url_v2_get_0(self):
        """Test case for fetch_one_video_by_url_v2_api_v1_kuaishou_web_fetch_one_video_by_url_v2_get_0

        根据链接获取单个作品数据V2/Fetch single video by URL V2  # noqa: E501
        """
        pass

    def test_fetch_one_video_comment_api_v1_kuaishou_web_fetch_one_video_comment_get(self):
        """Test case for fetch_one_video_comment_api_v1_kuaishou_web_fetch_one_video_comment_get

        获取单个作品评论数据/Get single video comment data  # noqa: E501
        """
        pass

    def test_fetch_one_video_comment_api_v1_kuaishou_web_fetch_one_video_comment_get_0(self):
        """Test case for fetch_one_video_comment_api_v1_kuaishou_web_fetch_one_video_comment_get_0

        获取单个作品评论数据/Get single video comment data  # noqa: E501
        """
        pass

    def test_fetch_one_video_v2_api_v1_kuaishou_web_fetch_one_video_v2_get(self):
        """Test case for fetch_one_video_v2_api_v1_kuaishou_web_fetch_one_video_v2_get

        快手单一视频查询接口V2/Kuaishou single video query API V2  # noqa: E501
        """
        pass

    def test_fetch_one_video_v2_api_v1_kuaishou_web_fetch_one_video_v2_get_0(self):
        """Test case for fetch_one_video_v2_api_v1_kuaishou_web_fetch_one_video_v2_get_0

        快手单一视频查询接口V2/Kuaishou single video query API V2  # noqa: E501
        """
        pass

    def test_fetch_user_info_api_v1_kuaishou_web_fetch_user_info_get(self):
        """Test case for fetch_user_info_api_v1_kuaishou_web_fetch_user_info_get

        获取主页信息数据/Get home page info data  # noqa: E501
        """
        pass

    def test_fetch_user_info_api_v1_kuaishou_web_fetch_user_info_get_0(self):
        """Test case for fetch_user_info_api_v1_kuaishou_web_fetch_user_info_get_0

        获取主页信息数据/Get home page info data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
