# coding: utf-8

"""
    TikHub.io - Your Ultimate Social Media Data & API Marketplace

    High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import tikhub_sdk_v2
from tikhub_sdk_v2.api.tik_tok_app_v3_api_api import TikTokAppV3APIApi  # noqa: E501
from tikhub_sdk_v2.rest import ApiException


class TestTikTokAppV3APIApi(unittest.TestCase):
    """TikTokAppV3APIApi unit test stubs"""

    def setUp(self):
        self.api = tikhub_sdk_v2.api.tik_tok_app_v3_api_api.TikTokAppV3APIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_video_play_count_api_v1_tiktok_app_v3_add_video_play_count_get(self):
        """Test case for add_video_play_count_api_v1_tiktok_app_v3_add_video_play_count_get

        根据视频ID来增加作品的播放数/Increase the number of plays of the work according to the video ID  # noqa: E501
        """
        pass

    def test_add_video_play_count_api_v1_tiktok_app_v3_add_video_play_count_get_0(self):
        """Test case for add_video_play_count_api_v1_tiktok_app_v3_add_video_play_count_get_0

        根据视频ID来增加作品的播放数/Increase the number of plays of the work according to the video ID  # noqa: E501
        """
        pass

    def test_add_video_play_count_api_v1_tiktok_app_v3_tikhub_internal_test20241122_get(self):
        """Test case for add_video_play_count_api_v1_tiktok_app_v3_tikhub_internal_test20241122_get

        TikHub内部测试接口/TikHub internal test interface  # noqa: E501
        """
        pass

    def test_add_video_play_count_api_v1_tiktok_app_v3_tikhub_internal_test20241122_get_0(self):
        """Test case for add_video_play_count_api_v1_tiktok_app_v3_tikhub_internal_test20241122_get_0

        TikHub内部测试接口/TikHub internal test interface  # noqa: E501
        """
        pass

    def test_check_live_room_online_api_v1_tiktok_app_v3_check_live_room_online_get(self):
        """Test case for check_live_room_online_api_v1_tiktok_app_v3_check_live_room_online_get

        检测直播间是否在线/Check if live room is online  # noqa: E501
        """
        pass

    def test_check_live_room_online_api_v1_tiktok_app_v3_check_live_room_online_get_0(self):
        """Test case for check_live_room_online_api_v1_tiktok_app_v3_check_live_room_online_get_0

        检测直播间是否在线/Check if live room is online  # noqa: E501
        """
        pass

    def test_encrypt_decrypt_login_request_api_v1_tiktok_app_v3_encrypt_decrypt_login_request_post(self):
        """Test case for encrypt_decrypt_login_request_api_v1_tiktok_app_v3_encrypt_decrypt_login_request_post

        加密或解密 TikTok APP 登录请求体/Encrypt or Decrypt TikTok APP login request body  # noqa: E501
        """
        pass

    def test_encrypt_decrypt_login_request_api_v1_tiktok_app_v3_encrypt_decrypt_login_request_post_0(self):
        """Test case for encrypt_decrypt_login_request_api_v1_tiktok_app_v3_encrypt_decrypt_login_request_post_0

        加密或解密 TikTok APP 登录请求体/Encrypt or Decrypt TikTok APP login request body  # noqa: E501
        """
        pass

    def test_fetch_content_translate_api_v1_tiktok_app_v3_fetch_content_translate_post(self):
        """Test case for fetch_content_translate_api_v1_tiktok_app_v3_fetch_content_translate_post

        获取内容翻译数据/Get content translation data  # noqa: E501
        """
        pass

    def test_fetch_content_translate_api_v1_tiktok_app_v3_fetch_content_translate_post_0(self):
        """Test case for fetch_content_translate_api_v1_tiktok_app_v3_fetch_content_translate_post_0

        获取内容翻译数据/Get content translation data  # noqa: E501
        """
        pass

    def test_fetch_creator_info_api_v1_tiktok_app_v3_fetch_creator_info_get(self):
        """Test case for fetch_creator_info_api_v1_tiktok_app_v3_fetch_creator_info_get

        获取创作者信息/Get creator information  # noqa: E501
        """
        pass

    def test_fetch_creator_info_api_v1_tiktok_app_v3_fetch_creator_info_get_0(self):
        """Test case for fetch_creator_info_api_v1_tiktok_app_v3_fetch_creator_info_get_0

        获取创作者信息/Get creator information  # noqa: E501
        """
        pass

    def test_fetch_creator_showcase_product_list_api_v1_tiktok_app_v3_fetch_creator_showcase_product_list_get(self):
        """Test case for fetch_creator_showcase_product_list_api_v1_tiktok_app_v3_fetch_creator_showcase_product_list_get

        获取创作者橱窗商品列表/Get creator showcase product list  # noqa: E501
        """
        pass

    def test_fetch_creator_showcase_product_list_api_v1_tiktok_app_v3_fetch_creator_showcase_product_list_get_0(self):
        """Test case for fetch_creator_showcase_product_list_api_v1_tiktok_app_v3_fetch_creator_showcase_product_list_get_0

        获取创作者橱窗商品列表/Get creator showcase product list  # noqa: E501
        """
        pass

    def test_fetch_general_search_result_api_v1_tiktok_app_v3_fetch_general_search_result_get(self):
        """Test case for fetch_general_search_result_api_v1_tiktok_app_v3_fetch_general_search_result_get

        获取指定关键词的综合搜索结果/Get comprehensive search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_general_search_result_api_v1_tiktok_app_v3_fetch_general_search_result_get_0(self):
        """Test case for fetch_general_search_result_api_v1_tiktok_app_v3_fetch_general_search_result_get_0

        获取指定关键词的综合搜索结果/Get comprehensive search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_hashtag_detail_api_v1_tiktok_app_v3_fetch_hashtag_detail_get(self):
        """Test case for fetch_hashtag_detail_api_v1_tiktok_app_v3_fetch_hashtag_detail_get

        获取指定话题的详情数据/Get details of specified hashtag  # noqa: E501
        """
        pass

    def test_fetch_hashtag_detail_api_v1_tiktok_app_v3_fetch_hashtag_detail_get_0(self):
        """Test case for fetch_hashtag_detail_api_v1_tiktok_app_v3_fetch_hashtag_detail_get_0

        获取指定话题的详情数据/Get details of specified hashtag  # noqa: E501
        """
        pass

    def test_fetch_hashtag_search_result_api_v1_tiktok_app_v3_fetch_hashtag_search_result_get(self):
        """Test case for fetch_hashtag_search_result_api_v1_tiktok_app_v3_fetch_hashtag_search_result_get

        获取指定关键词的话题搜索结果/Get hashtag search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_hashtag_search_result_api_v1_tiktok_app_v3_fetch_hashtag_search_result_get_0(self):
        """Test case for fetch_hashtag_search_result_api_v1_tiktok_app_v3_fetch_hashtag_search_result_get_0

        获取指定关键词的话题搜索结果/Get hashtag search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_hashtag_video_list_api_v1_tiktok_app_v3_fetch_hashtag_video_list_get(self):
        """Test case for fetch_hashtag_video_list_api_v1_tiktok_app_v3_fetch_hashtag_video_list_get

        获取指定话题的作品数据/Get video list of specified hashtag  # noqa: E501
        """
        pass

    def test_fetch_hashtag_video_list_api_v1_tiktok_app_v3_fetch_hashtag_video_list_get_0(self):
        """Test case for fetch_hashtag_video_list_api_v1_tiktok_app_v3_fetch_hashtag_video_list_get_0

        获取指定话题的作品数据/Get video list of specified hashtag  # noqa: E501
        """
        pass

    def test_fetch_home_feed_api_v1_tiktok_app_v3_fetch_home_feed_get(self):
        """Test case for fetch_home_feed_api_v1_tiktok_app_v3_fetch_home_feed_get

        获取主页视频推荐数据/Get home feed(recommend) video data  # noqa: E501
        """
        pass

    def test_fetch_home_feed_api_v1_tiktok_app_v3_fetch_home_feed_get_0(self):
        """Test case for fetch_home_feed_api_v1_tiktok_app_v3_fetch_home_feed_get_0

        获取主页视频推荐数据/Get home feed(recommend) video data  # noqa: E501
        """
        pass

    def test_fetch_live_daily_rank_api_v1_tiktok_app_v3_fetch_live_daily_rank_get(self):
        """Test case for fetch_live_daily_rank_api_v1_tiktok_app_v3_fetch_live_daily_rank_get

        获取直播每日榜单数据/Get live daily rank data  # noqa: E501
        """
        pass

    def test_fetch_live_daily_rank_api_v1_tiktok_app_v3_fetch_live_daily_rank_get_0(self):
        """Test case for fetch_live_daily_rank_api_v1_tiktok_app_v3_fetch_live_daily_rank_get_0

        获取直播每日榜单数据/Get live daily rank data  # noqa: E501
        """
        pass

    def test_fetch_live_ranking_list_api_v1_tiktok_app_v3_fetch_live_ranking_list_get(self):
        """Test case for fetch_live_ranking_list_api_v1_tiktok_app_v3_fetch_live_ranking_list_get

        获取直播间排行榜数据/Get live room ranking list  # noqa: E501
        """
        pass

    def test_fetch_live_ranking_list_api_v1_tiktok_app_v3_fetch_live_ranking_list_get_0(self):
        """Test case for fetch_live_ranking_list_api_v1_tiktok_app_v3_fetch_live_ranking_list_get_0

        获取直播间排行榜数据/Get live room ranking list  # noqa: E501
        """
        pass

    def test_fetch_live_room_info_api_v1_tiktok_app_v3_fetch_live_room_info_get(self):
        """Test case for fetch_live_room_info_api_v1_tiktok_app_v3_fetch_live_room_info_get

        获取指定直播间的数据/Get data of specified live room  # noqa: E501
        """
        pass

    def test_fetch_live_room_info_api_v1_tiktok_app_v3_fetch_live_room_info_get_0(self):
        """Test case for fetch_live_room_info_api_v1_tiktok_app_v3_fetch_live_room_info_get_0

        获取指定直播间的数据/Get data of specified live room  # noqa: E501
        """
        pass

    def test_fetch_live_room_product_list_api_v1_tiktok_app_v3_fetch_live_room_product_list_get(self):
        """Test case for fetch_live_room_product_list_api_v1_tiktok_app_v3_fetch_live_room_product_list_get

        获取直播间商品列表数据/Get live room product list data  # noqa: E501
        """
        pass

    def test_fetch_live_room_product_list_api_v1_tiktok_app_v3_fetch_live_room_product_list_get_0(self):
        """Test case for fetch_live_room_product_list_api_v1_tiktok_app_v3_fetch_live_room_product_list_get_0

        获取直播间商品列表数据/Get live room product list data  # noqa: E501
        """
        pass

    def test_fetch_live_search_result_api_v1_tiktok_app_v3_fetch_live_search_result_get(self):
        """Test case for fetch_live_search_result_api_v1_tiktok_app_v3_fetch_live_search_result_get

        获取指定关键词的直播搜索结果/Get live search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_live_search_result_api_v1_tiktok_app_v3_fetch_live_search_result_get_0(self):
        """Test case for fetch_live_search_result_api_v1_tiktok_app_v3_fetch_live_search_result_get_0

        获取指定关键词的直播搜索结果/Get live search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_location_search_api_v1_tiktok_app_v3_fetch_location_search_get(self):
        """Test case for fetch_location_search_api_v1_tiktok_app_v3_fetch_location_search_get

        获取地点搜索结果/Get location search results  # noqa: E501
        """
        pass

    def test_fetch_location_search_api_v1_tiktok_app_v3_fetch_location_search_get_0(self):
        """Test case for fetch_location_search_api_v1_tiktok_app_v3_fetch_location_search_get_0

        获取地点搜索结果/Get location search results  # noqa: E501
        """
        pass

    def test_fetch_multi_video_api_v1_tiktok_app_v3_fetch_multi_video_post(self):
        """Test case for fetch_multi_video_api_v1_tiktok_app_v3_fetch_multi_video_post

        批量获取视频信息/Batch Get Video Information  # noqa: E501
        """
        pass

    def test_fetch_multi_video_api_v1_tiktok_app_v3_fetch_multi_video_post_0(self):
        """Test case for fetch_multi_video_api_v1_tiktok_app_v3_fetch_multi_video_post_0

        批量获取视频信息/Batch Get Video Information  # noqa: E501
        """
        pass

    def test_fetch_multi_video_v2_api_v1_tiktok_app_v3_fetch_multi_video_v2_post(self):
        """Test case for fetch_multi_video_v2_api_v1_tiktok_app_v3_fetch_multi_video_v2_post

        批量获取视频信息 V2/Batch Get Video Information V2  # noqa: E501
        """
        pass

    def test_fetch_multi_video_v2_api_v1_tiktok_app_v3_fetch_multi_video_v2_post_0(self):
        """Test case for fetch_multi_video_v2_api_v1_tiktok_app_v3_fetch_multi_video_v2_post_0

        批量获取视频信息 V2/Batch Get Video Information V2  # noqa: E501
        """
        pass

    def test_fetch_music_detail_api_v1_tiktok_app_v3_fetch_music_detail_get(self):
        """Test case for fetch_music_detail_api_v1_tiktok_app_v3_fetch_music_detail_get

        获取指定音乐的详情数据/Get details of specified music  # noqa: E501
        """
        pass

    def test_fetch_music_detail_api_v1_tiktok_app_v3_fetch_music_detail_get_0(self):
        """Test case for fetch_music_detail_api_v1_tiktok_app_v3_fetch_music_detail_get_0

        获取指定音乐的详情数据/Get details of specified music  # noqa: E501
        """
        pass

    def test_fetch_music_search_result_api_v1_tiktok_app_v3_fetch_music_search_result_get(self):
        """Test case for fetch_music_search_result_api_v1_tiktok_app_v3_fetch_music_search_result_get

        获取指定关键词的音乐搜索结果/Get music search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_music_search_result_api_v1_tiktok_app_v3_fetch_music_search_result_get_0(self):
        """Test case for fetch_music_search_result_api_v1_tiktok_app_v3_fetch_music_search_result_get_0

        获取指定关键词的音乐搜索结果/Get music search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_music_video_list_api_v1_tiktok_app_v3_fetch_music_video_list_get(self):
        """Test case for fetch_music_video_list_api_v1_tiktok_app_v3_fetch_music_video_list_get

        获取指定音乐的视频列表数据/Get video list of specified music  # noqa: E501
        """
        pass

    def test_fetch_music_video_list_api_v1_tiktok_app_v3_fetch_music_video_list_get_0(self):
        """Test case for fetch_music_video_list_api_v1_tiktok_app_v3_fetch_music_video_list_get_0

        获取指定音乐的视频列表数据/Get video list of specified music  # noqa: E501
        """
        pass

    def test_fetch_one_video_api_v1_tiktok_app_v3_fetch_one_video_get(self):
        """Test case for fetch_one_video_api_v1_tiktok_app_v3_fetch_one_video_get

        获取单个作品数据/Get single video data  # noqa: E501
        """
        pass

    def test_fetch_one_video_api_v1_tiktok_app_v3_fetch_one_video_get_0(self):
        """Test case for fetch_one_video_api_v1_tiktok_app_v3_fetch_one_video_get_0

        获取单个作品数据/Get single video data  # noqa: E501
        """
        pass

    def test_fetch_one_video_by_share_url_api_v1_tiktok_app_v3_fetch_one_video_by_share_url_get(self):
        """Test case for fetch_one_video_by_share_url_api_v1_tiktok_app_v3_fetch_one_video_by_share_url_get

        根据分享链接获取单个作品数据/Get single video data by sharing link  # noqa: E501
        """
        pass

    def test_fetch_one_video_by_share_url_api_v1_tiktok_app_v3_fetch_one_video_by_share_url_get_0(self):
        """Test case for fetch_one_video_by_share_url_api_v1_tiktok_app_v3_fetch_one_video_by_share_url_get_0

        根据分享链接获取单个作品数据/Get single video data by sharing link  # noqa: E501
        """
        pass

    def test_fetch_one_video_v2_api_v1_tiktok_app_v3_fetch_one_video_v2_get(self):
        """Test case for fetch_one_video_v2_api_v1_tiktok_app_v3_fetch_one_video_v2_get

        获取单个作品数据 V2/Get single video data V2  # noqa: E501
        """
        pass

    def test_fetch_one_video_v2_api_v1_tiktok_app_v3_fetch_one_video_v2_get_0(self):
        """Test case for fetch_one_video_v2_api_v1_tiktok_app_v3_fetch_one_video_v2_get_0

        获取单个作品数据 V2/Get single video data V2  # noqa: E501
        """
        pass

    def test_fetch_product_detail_api_v1_tiktok_app_v3_fetch_product_detail_get(self):
        """Test case for fetch_product_detail_api_v1_tiktok_app_v3_fetch_product_detail_get

        获取商品详情数据（即将弃用，使用 fetch_product_detail_v2 代替）/Get product detail data (will be deprecated, use fetch_product_detail_v2 instead)  # noqa: E501
        """
        pass

    def test_fetch_product_detail_api_v1_tiktok_app_v3_fetch_product_detail_get_0(self):
        """Test case for fetch_product_detail_api_v1_tiktok_app_v3_fetch_product_detail_get_0

        获取商品详情数据（即将弃用，使用 fetch_product_detail_v2 代替）/Get product detail data (will be deprecated, use fetch_product_detail_v2 instead)  # noqa: E501
        """
        pass

    def test_fetch_product_detail_v2_api_v1_tiktok_app_v3_fetch_product_detail_v2_get(self):
        """Test case for fetch_product_detail_v2_api_v1_tiktok_app_v3_fetch_product_detail_v2_get

        获取商品详情数据V2/Get product detail data V2  # noqa: E501
        """
        pass

    def test_fetch_product_detail_v2_api_v1_tiktok_app_v3_fetch_product_detail_v2_get_0(self):
        """Test case for fetch_product_detail_v2_api_v1_tiktok_app_v3_fetch_product_detail_v2_get_0

        获取商品详情数据V2/Get product detail data V2  # noqa: E501
        """
        pass

    def test_fetch_product_detail_v3_api_v1_tiktok_app_v3_fetch_product_detail_v3_get(self):
        """Test case for fetch_product_detail_v3_api_v1_tiktok_app_v3_fetch_product_detail_v3_get

        获取商品详情数据V3/Get product detail data V3  # noqa: E501
        """
        pass

    def test_fetch_product_detail_v3_api_v1_tiktok_app_v3_fetch_product_detail_v3_get_0(self):
        """Test case for fetch_product_detail_v3_api_v1_tiktok_app_v3_fetch_product_detail_v3_get_0

        获取商品详情数据V3/Get product detail data V3  # noqa: E501
        """
        pass

    def test_fetch_product_id_by_share_link_api_v1_tiktok_app_v3_fetch_product_id_by_share_link_get(self):
        """Test case for fetch_product_id_by_share_link_api_v1_tiktok_app_v3_fetch_product_id_by_share_link_get

        通过分享链接获取商品ID/Get Product ID by Share Link  # noqa: E501
        """
        pass

    def test_fetch_product_id_by_share_link_api_v1_tiktok_app_v3_fetch_product_id_by_share_link_get_0(self):
        """Test case for fetch_product_id_by_share_link_api_v1_tiktok_app_v3_fetch_product_id_by_share_link_get_0

        通过分享链接获取商品ID/Get Product ID by Share Link  # noqa: E501
        """
        pass

    def test_fetch_product_review_api_v1_tiktok_app_v3_fetch_product_review_get(self):
        """Test case for fetch_product_review_api_v1_tiktok_app_v3_fetch_product_review_get

        获取商品评价数据/Get product review data  # noqa: E501
        """
        pass

    def test_fetch_product_review_api_v1_tiktok_app_v3_fetch_product_review_get_0(self):
        """Test case for fetch_product_review_api_v1_tiktok_app_v3_fetch_product_review_get_0

        获取商品评价数据/Get product review data  # noqa: E501
        """
        pass

    def test_fetch_product_search_api_v1_tiktok_app_v3_fetch_product_search_get(self):
        """Test case for fetch_product_search_api_v1_tiktok_app_v3_fetch_product_search_get

        获取商品搜索结果/Get product search results  # noqa: E501
        """
        pass

    def test_fetch_product_search_api_v1_tiktok_app_v3_fetch_product_search_get_0(self):
        """Test case for fetch_product_search_api_v1_tiktok_app_v3_fetch_product_search_get_0

        获取商品搜索结果/Get product search results  # noqa: E501
        """
        pass

    def test_fetch_share_qr_code_api_v1_tiktok_app_v3_fetch_share_qr_code_get(self):
        """Test case for fetch_share_qr_code_api_v1_tiktok_app_v3_fetch_share_qr_code_get

        获取分享二维码/Get share QR code  # noqa: E501
        """
        pass

    def test_fetch_share_qr_code_api_v1_tiktok_app_v3_fetch_share_qr_code_get_0(self):
        """Test case for fetch_share_qr_code_api_v1_tiktok_app_v3_fetch_share_qr_code_get_0

        获取分享二维码/Get share QR code  # noqa: E501
        """
        pass

    def test_fetch_share_short_link_api_v1_tiktok_app_v3_fetch_share_short_link_get(self):
        """Test case for fetch_share_short_link_api_v1_tiktok_app_v3_fetch_share_short_link_get

        获取分享短链接/Get share short link  # noqa: E501
        """
        pass

    def test_fetch_share_short_link_api_v1_tiktok_app_v3_fetch_share_short_link_get_0(self):
        """Test case for fetch_share_short_link_api_v1_tiktok_app_v3_fetch_share_short_link_get_0

        获取分享短链接/Get share short link  # noqa: E501
        """
        pass

    def test_fetch_shop_home_api_v1_tiktok_app_v3_fetch_shop_home_get(self):
        """Test case for fetch_shop_home_api_v1_tiktok_app_v3_fetch_shop_home_get

        获取商家主页数据/Get shop home page data  # noqa: E501
        """
        pass

    def test_fetch_shop_home_api_v1_tiktok_app_v3_fetch_shop_home_get_0(self):
        """Test case for fetch_shop_home_api_v1_tiktok_app_v3_fetch_shop_home_get_0

        获取商家主页数据/Get shop home page data  # noqa: E501
        """
        pass

    def test_fetch_shop_home_page_list_api_v1_tiktok_app_v3_fetch_shop_home_page_list_get(self):
        """Test case for fetch_shop_home_page_list_api_v1_tiktok_app_v3_fetch_shop_home_page_list_get

        获取商家主页Page列表数据/Get shop home page list data  # noqa: E501
        """
        pass

    def test_fetch_shop_home_page_list_api_v1_tiktok_app_v3_fetch_shop_home_page_list_get_0(self):
        """Test case for fetch_shop_home_page_list_api_v1_tiktok_app_v3_fetch_shop_home_page_list_get_0

        获取商家主页Page列表数据/Get shop home page list data  # noqa: E501
        """
        pass

    def test_fetch_shop_id_by_share_link_api_v1_tiktok_app_v3_fetch_shop_id_by_share_link_get(self):
        """Test case for fetch_shop_id_by_share_link_api_v1_tiktok_app_v3_fetch_shop_id_by_share_link_get

        通过分享链接获取店铺ID/Get Shop ID by Share Link  # noqa: E501
        """
        pass

    def test_fetch_shop_id_by_share_link_api_v1_tiktok_app_v3_fetch_shop_id_by_share_link_get_0(self):
        """Test case for fetch_shop_id_by_share_link_api_v1_tiktok_app_v3_fetch_shop_id_by_share_link_get_0

        通过分享链接获取店铺ID/Get Shop ID by Share Link  # noqa: E501
        """
        pass

    def test_fetch_shop_info_api_v1_tiktok_app_v3_fetch_shop_info_get(self):
        """Test case for fetch_shop_info_api_v1_tiktok_app_v3_fetch_shop_info_get

        获取商家信息数据/Get shop information data  # noqa: E501
        """
        pass

    def test_fetch_shop_info_api_v1_tiktok_app_v3_fetch_shop_info_get_0(self):
        """Test case for fetch_shop_info_api_v1_tiktok_app_v3_fetch_shop_info_get_0

        获取商家信息数据/Get shop information data  # noqa: E501
        """
        pass

    def test_fetch_shop_product_category_api_v1_tiktok_app_v3_fetch_shop_product_category_get(self):
        """Test case for fetch_shop_product_category_api_v1_tiktok_app_v3_fetch_shop_product_category_get

        获取商家产品分类数据/Get shop product category data  # noqa: E501
        """
        pass

    def test_fetch_shop_product_category_api_v1_tiktok_app_v3_fetch_shop_product_category_get_0(self):
        """Test case for fetch_shop_product_category_api_v1_tiktok_app_v3_fetch_shop_product_category_get_0

        获取商家产品分类数据/Get shop product category data  # noqa: E501
        """
        pass

    def test_fetch_shop_product_list_api_v1_tiktok_app_v3_fetch_shop_product_list_get(self):
        """Test case for fetch_shop_product_list_api_v1_tiktok_app_v3_fetch_shop_product_list_get

        获取商家商品列表数据/Get shop product list data  # noqa: E501
        """
        pass

    def test_fetch_shop_product_list_api_v1_tiktok_app_v3_fetch_shop_product_list_get_0(self):
        """Test case for fetch_shop_product_list_api_v1_tiktok_app_v3_fetch_shop_product_list_get_0

        获取商家商品列表数据/Get shop product list data  # noqa: E501
        """
        pass

    def test_fetch_shop_product_list_v2_api_v1_tiktok_app_v3_fetch_shop_product_list_v2_get(self):
        """Test case for fetch_shop_product_list_v2_api_v1_tiktok_app_v3_fetch_shop_product_list_v2_get

        获取商家商品列表数据 V2/Get shop product list data V2  # noqa: E501
        """
        pass

    def test_fetch_shop_product_list_v2_api_v1_tiktok_app_v3_fetch_shop_product_list_v2_get_0(self):
        """Test case for fetch_shop_product_list_v2_api_v1_tiktok_app_v3_fetch_shop_product_list_v2_get_0

        获取商家商品列表数据 V2/Get shop product list data V2  # noqa: E501
        """
        pass

    def test_fetch_shop_product_recommend_api_v1_tiktok_app_v3_fetch_shop_product_recommend_get(self):
        """Test case for fetch_shop_product_recommend_api_v1_tiktok_app_v3_fetch_shop_product_recommend_get

        获取商家商品推荐数据/Get shop product recommend data  # noqa: E501
        """
        pass

    def test_fetch_shop_product_recommend_api_v1_tiktok_app_v3_fetch_shop_product_recommend_get_0(self):
        """Test case for fetch_shop_product_recommend_api_v1_tiktok_app_v3_fetch_shop_product_recommend_get_0

        获取商家商品推荐数据/Get shop product recommend data  # noqa: E501
        """
        pass

    def test_fetch_user_follower_list_api_v1_tiktok_app_v3_fetch_user_follower_list_get(self):
        """Test case for fetch_user_follower_list_api_v1_tiktok_app_v3_fetch_user_follower_list_get

        获取指定用户的粉丝列表数据/Get follower list of specified user  # noqa: E501
        """
        pass

    def test_fetch_user_follower_list_api_v1_tiktok_app_v3_fetch_user_follower_list_get_0(self):
        """Test case for fetch_user_follower_list_api_v1_tiktok_app_v3_fetch_user_follower_list_get_0

        获取指定用户的粉丝列表数据/Get follower list of specified user  # noqa: E501
        """
        pass

    def test_fetch_user_following_list_api_v1_tiktok_app_v3_fetch_user_following_list_get(self):
        """Test case for fetch_user_following_list_api_v1_tiktok_app_v3_fetch_user_following_list_get

        获取指定用户的关注列表数据/Get following list of specified user  # noqa: E501
        """
        pass

    def test_fetch_user_following_list_api_v1_tiktok_app_v3_fetch_user_following_list_get_0(self):
        """Test case for fetch_user_following_list_api_v1_tiktok_app_v3_fetch_user_following_list_get_0

        获取指定用户的关注列表数据/Get following list of specified user  # noqa: E501
        """
        pass

    def test_fetch_user_like_videos_api_v1_tiktok_app_v3_fetch_user_like_videos_get(self):
        """Test case for fetch_user_like_videos_api_v1_tiktok_app_v3_fetch_user_like_videos_get

        获取用户喜欢作品数据/Get user like video data  # noqa: E501
        """
        pass

    def test_fetch_user_like_videos_api_v1_tiktok_app_v3_fetch_user_like_videos_get_0(self):
        """Test case for fetch_user_like_videos_api_v1_tiktok_app_v3_fetch_user_like_videos_get_0

        获取用户喜欢作品数据/Get user like video data  # noqa: E501
        """
        pass

    def test_fetch_user_music_list_api_v1_tiktok_app_v3_fetch_user_music_list_get(self):
        """Test case for fetch_user_music_list_api_v1_tiktok_app_v3_fetch_user_music_list_get

        获取用户音乐列表数据/Get user music list data  # noqa: E501
        """
        pass

    def test_fetch_user_music_list_api_v1_tiktok_app_v3_fetch_user_music_list_get_0(self):
        """Test case for fetch_user_music_list_api_v1_tiktok_app_v3_fetch_user_music_list_get_0

        获取用户音乐列表数据/Get user music list data  # noqa: E501
        """
        pass

    def test_fetch_user_post_videos_api_v1_tiktok_app_v3_fetch_user_post_videos_get(self):
        """Test case for fetch_user_post_videos_api_v1_tiktok_app_v3_fetch_user_post_videos_get

        获取用户主页作品数据/Get user homepage video data  # noqa: E501
        """
        pass

    def test_fetch_user_post_videos_api_v1_tiktok_app_v3_fetch_user_post_videos_get_0(self):
        """Test case for fetch_user_post_videos_api_v1_tiktok_app_v3_fetch_user_post_videos_get_0

        获取用户主页作品数据/Get user homepage video data  # noqa: E501
        """
        pass

    def test_fetch_user_repost_videos_api_v1_tiktok_app_v3_fetch_user_repost_videos_get(self):
        """Test case for fetch_user_repost_videos_api_v1_tiktok_app_v3_fetch_user_repost_videos_get

        获取用户转发的作品数据/Get user repost video data  # noqa: E501
        """
        pass

    def test_fetch_user_repost_videos_api_v1_tiktok_app_v3_fetch_user_repost_videos_get_0(self):
        """Test case for fetch_user_repost_videos_api_v1_tiktok_app_v3_fetch_user_repost_videos_get_0

        获取用户转发的作品数据/Get user repost video data  # noqa: E501
        """
        pass

    def test_fetch_user_search_result_api_v1_tiktok_app_v3_fetch_user_search_result_get(self):
        """Test case for fetch_user_search_result_api_v1_tiktok_app_v3_fetch_user_search_result_get

        获取指定关键词的用户搜索结果/Get user search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_user_search_result_api_v1_tiktok_app_v3_fetch_user_search_result_get_0(self):
        """Test case for fetch_user_search_result_api_v1_tiktok_app_v3_fetch_user_search_result_get_0

        获取指定关键词的用户搜索结果/Get user search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_video_comments_api_v1_tiktok_app_v3_fetch_video_comments_get(self):
        """Test case for fetch_video_comments_api_v1_tiktok_app_v3_fetch_video_comments_get

        获取单个视频评论数据/Get single video comments data  # noqa: E501
        """
        pass

    def test_fetch_video_comments_api_v1_tiktok_app_v3_fetch_video_comments_get_0(self):
        """Test case for fetch_video_comments_api_v1_tiktok_app_v3_fetch_video_comments_get_0

        获取单个视频评论数据/Get single video comments data  # noqa: E501
        """
        pass

    def test_fetch_video_comments_reply_api_v1_tiktok_app_v3_fetch_video_comment_replies_get(self):
        """Test case for fetch_video_comments_reply_api_v1_tiktok_app_v3_fetch_video_comment_replies_get

        获取指定视频的评论回复数据/Get comment replies data of specified video  # noqa: E501
        """
        pass

    def test_fetch_video_comments_reply_api_v1_tiktok_app_v3_fetch_video_comment_replies_get_0(self):
        """Test case for fetch_video_comments_reply_api_v1_tiktok_app_v3_fetch_video_comment_replies_get_0

        获取指定视频的评论回复数据/Get comment replies data of specified video  # noqa: E501
        """
        pass

    def test_fetch_video_search_result_api_v1_tiktok_app_v3_fetch_video_search_result_get(self):
        """Test case for fetch_video_search_result_api_v1_tiktok_app_v3_fetch_video_search_result_get

        获取指定关键词的视频搜索结果/Get video search results of specified keywords  # noqa: E501
        """
        pass

    def test_fetch_video_search_result_api_v1_tiktok_app_v3_fetch_video_search_result_get_0(self):
        """Test case for fetch_video_search_result_api_v1_tiktok_app_v3_fetch_video_search_result_get_0

        获取指定关键词的视频搜索结果/Get video search results of specified keywords  # noqa: E501
        """
        pass

    def test_handler_user_profile_api_v1_tiktok_app_v3_handler_user_profile_get(self):
        """Test case for handler_user_profile_api_v1_tiktok_app_v3_handler_user_profile_get

        获取指定用户的信息/Get information of specified user  # noqa: E501
        """
        pass

    def test_handler_user_profile_api_v1_tiktok_app_v3_handler_user_profile_get_0(self):
        """Test case for handler_user_profile_api_v1_tiktok_app_v3_handler_user_profile_get_0

        获取指定用户的信息/Get information of specified user  # noqa: E501
        """
        pass

    def test_open_tiktok_app_to_keyword_search_api_v1_tiktok_app_v3_open_tiktok_app_to_keyword_search_get(self):
        """Test case for open_tiktok_app_to_keyword_search_api_v1_tiktok_app_v3_open_tiktok_app_to_keyword_search_get

        生成TikTok分享链接，唤起TikTok APP，跳转指定关键词搜索结果/Generate TikTok share link, call TikTok APP, and jump to the specified keyword search result  # noqa: E501
        """
        pass

    def test_open_tiktok_app_to_keyword_search_api_v1_tiktok_app_v3_open_tiktok_app_to_keyword_search_get_0(self):
        """Test case for open_tiktok_app_to_keyword_search_api_v1_tiktok_app_v3_open_tiktok_app_to_keyword_search_get_0

        生成TikTok分享链接，唤起TikTok APP，跳转指定关键词搜索结果/Generate TikTok share link, call TikTok APP, and jump to the specified keyword search result  # noqa: E501
        """
        pass

    def test_open_tiktok_app_to_send_private_message_api_v1_tiktok_app_v3_open_tiktok_app_to_send_private_message_get(self):
        """Test case for open_tiktok_app_to_send_private_message_api_v1_tiktok_app_v3_open_tiktok_app_to_send_private_message_get

        生成TikTok分享链接，唤起TikTok APP，给指定用户发送私信/Generate TikTok share link, call TikTok APP, and send private messages to specified users  # noqa: E501
        """
        pass

    def test_open_tiktok_app_to_send_private_message_api_v1_tiktok_app_v3_open_tiktok_app_to_send_private_message_get_0(self):
        """Test case for open_tiktok_app_to_send_private_message_api_v1_tiktok_app_v3_open_tiktok_app_to_send_private_message_get_0

        生成TikTok分享链接，唤起TikTok APP，给指定用户发送私信/Generate TikTok share link, call TikTok APP, and send private messages to specified users  # noqa: E501
        """
        pass

    def test_open_tiktok_app_to_user_profile_api_v1_tiktok_app_v3_open_tiktok_app_to_user_profile_get(self):
        """Test case for open_tiktok_app_to_user_profile_api_v1_tiktok_app_v3_open_tiktok_app_to_user_profile_get

        生成TikTok分享链接，唤起TikTok APP，跳转指定用户主页/Generate TikTok share link, call TikTok APP, and jump to the specified user profile  # noqa: E501
        """
        pass

    def test_open_tiktok_app_to_user_profile_api_v1_tiktok_app_v3_open_tiktok_app_to_user_profile_get_0(self):
        """Test case for open_tiktok_app_to_user_profile_api_v1_tiktok_app_v3_open_tiktok_app_to_user_profile_get_0

        生成TikTok分享链接，唤起TikTok APP，跳转指定用户主页/Generate TikTok share link, call TikTok APP, and jump to the specified user profile  # noqa: E501
        """
        pass

    def test_open_tiktok_app_to_video_detail_api_v1_tiktok_app_v3_open_tiktok_app_to_video_detail_get(self):
        """Test case for open_tiktok_app_to_video_detail_api_v1_tiktok_app_v3_open_tiktok_app_to_video_detail_get

        生成TikTok分享链接，唤起TikTok APP，跳转指定作品详情页/Generate TikTok share link, call TikTok APP, and jump to the specified video details page  # noqa: E501
        """
        pass

    def test_open_tiktok_app_to_video_detail_api_v1_tiktok_app_v3_open_tiktok_app_to_video_detail_get_0(self):
        """Test case for open_tiktok_app_to_video_detail_api_v1_tiktok_app_v3_open_tiktok_app_to_video_detail_get_0

        生成TikTok分享链接，唤起TikTok APP，跳转指定作品详情页/Generate TikTok share link, call TikTok APP, and jump to the specified video details page  # noqa: E501
        """
        pass

    def test_register_device_api_v1_tiktok_app_v3_register_device_get(self):
        """Test case for register_device_api_v1_tiktok_app_v3_register_device_get

        注册设备信息/Register device information  # noqa: E501
        """
        pass

    def test_register_device_api_v1_tiktok_app_v3_register_device_get_0(self):
        """Test case for register_device_api_v1_tiktok_app_v3_register_device_get_0

        注册设备信息/Register device information  # noqa: E501
        """
        pass

    def test_t_tencrypt_algorithm_api_v1_tiktok_app_v3_t_tencrypt_algorithm_post(self):
        """Test case for t_tencrypt_algorithm_api_v1_tiktok_app_v3_t_tencrypt_algorithm_post

        TikTok APP加密算法/TikTok APP encryption algorithm  # noqa: E501
        """
        pass

    def test_t_tencrypt_algorithm_api_v1_tiktok_app_v3_t_tencrypt_algorithm_post_0(self):
        """Test case for t_tencrypt_algorithm_api_v1_tiktok_app_v3_t_tencrypt_algorithm_post_0

        TikTok APP加密算法/TikTok APP encryption algorithm  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
