# coding: utf-8

"""
    TikHub.io - Your Ultimate Social Media Data & API Marketplace

    High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tikhub_sdk_v2
from tikhub_sdk_v2.models.body_fetch_hot_calendar_list_api_v1_douyin_billboard_fetch_hot_calendar_list_post import BodyFetchHotCalendarListApiV1DouyinBillboardFetchHotCalendarListPost  # noqa: E501
from tikhub_sdk_v2.rest import ApiException

class TestBodyFetchHotCalendarListApiV1DouyinBillboardFetchHotCalendarListPost(unittest.TestCase):
    """BodyFetchHotCalendarListApiV1DouyinBillboardFetchHotCalendarListPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BodyFetchHotCalendarListApiV1DouyinBillboardFetchHotCalendarListPost
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tikhub_sdk_v2.models.body_fetch_hot_calendar_list_api_v1_douyin_billboard_fetch_hot_calendar_list_post.BodyFetchHotCalendarListApiV1DouyinBillboardFetchHotCalendarListPost()  # noqa: E501
        if include_optional :
            return BodyFetchHotCalendarListApiV1DouyinBillboardFetchHotCalendarListPost(
                city_code = '0', 
                category_code = '0', 
                end_date = 56, 
                start_date = 56
            )
        else :
            return BodyFetchHotCalendarListApiV1DouyinBillboardFetchHotCalendarListPost(
        )

    def testBodyFetchHotCalendarListApiV1DouyinBillboardFetchHotCalendarListPost(self):
        """Test BodyFetchHotCalendarListApiV1DouyinBillboardFetchHotCalendarListPost"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
