# coding: utf-8

"""
    TikHub.io - Your Ultimate Social Media Data & API Marketplace

    High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import tikhub_sdk_v2
from tikhub_sdk_v2.api.xiaohongshu_web_api_api import XiaohongshuWebAPIApi  # noqa: E501
from tikhub_sdk_v2.rest import ApiException


class TestXiaohongshuWebAPIApi(unittest.TestCase):
    """XiaohongshuWebAPIApi unit test stubs"""

    def setUp(self):
        self.api = tikhub_sdk_v2.api.xiaohongshu_web_api_api.XiaohongshuWebAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_home_recommend_api_v1_xiaohongshu_web_get_home_recommend_post(self):
        """Test case for get_home_recommend_api_v1_xiaohongshu_web_get_home_recommend_post

        获取首页推荐/Get home recommend  # noqa: E501
        """
        pass

    def test_get_home_recommend_api_v1_xiaohongshu_web_get_home_recommend_post_0(self):
        """Test case for get_home_recommend_api_v1_xiaohongshu_web_get_home_recommend_post_0

        获取首页推荐/Get home recommend  # noqa: E501
        """
        pass

    def test_get_note_comment_replies_api_v1_xiaohongshu_web_get_note_comment_replies_get(self):
        """Test case for get_note_comment_replies_api_v1_xiaohongshu_web_get_note_comment_replies_get

        获取笔记评论回复 V1/Get note comment replies V1  # noqa: E501
        """
        pass

    def test_get_note_comment_replies_api_v1_xiaohongshu_web_get_note_comment_replies_get_0(self):
        """Test case for get_note_comment_replies_api_v1_xiaohongshu_web_get_note_comment_replies_get_0

        获取笔记评论回复 V1/Get note comment replies V1  # noqa: E501
        """
        pass

    def test_get_note_comment_replies_api_v1_xiaohongshu_web_get_note_comment_replies_v2_get(self):
        """Test case for get_note_comment_replies_api_v1_xiaohongshu_web_get_note_comment_replies_v2_get

        获取笔记评论回复 V2/Get note comment replies V2  # noqa: E501
        """
        pass

    def test_get_note_comment_replies_api_v1_xiaohongshu_web_get_note_comment_replies_v2_get_0(self):
        """Test case for get_note_comment_replies_api_v1_xiaohongshu_web_get_note_comment_replies_v2_get_0

        获取笔记评论回复 V2/Get note comment replies V2  # noqa: E501
        """
        pass

    def test_get_note_comments_api_v1_xiaohongshu_web_get_note_comments_get(self):
        """Test case for get_note_comments_api_v1_xiaohongshu_web_get_note_comments_get

        获取笔记评论 V1/Get note comments V1  # noqa: E501
        """
        pass

    def test_get_note_comments_api_v1_xiaohongshu_web_get_note_comments_get_0(self):
        """Test case for get_note_comments_api_v1_xiaohongshu_web_get_note_comments_get_0

        获取笔记评论 V1/Get note comments V1  # noqa: E501
        """
        pass

    def test_get_note_comments_api_v1_xiaohongshu_web_get_note_comments_v2_get(self):
        """Test case for get_note_comments_api_v1_xiaohongshu_web_get_note_comments_v2_get

        获取笔记评论 V2/Get note comments V2  # noqa: E501
        """
        pass

    def test_get_note_comments_api_v1_xiaohongshu_web_get_note_comments_v2_get_0(self):
        """Test case for get_note_comments_api_v1_xiaohongshu_web_get_note_comments_v2_get_0

        获取笔记评论 V2/Get note comments V2  # noqa: E501
        """
        pass

    def test_get_note_id_and_xsec_token_api_v1_xiaohongshu_web_get_note_id_and_xsec_token_get(self):
        """Test case for get_note_id_and_xsec_token_api_v1_xiaohongshu_web_get_note_id_and_xsec_token_get

        通过分享链接获取小红书的Note ID 和 xsec_token/Get Xiaohongshu Note ID and xsec_token by share link  # noqa: E501
        """
        pass

    def test_get_note_id_and_xsec_token_api_v1_xiaohongshu_web_get_note_id_and_xsec_token_get_0(self):
        """Test case for get_note_id_and_xsec_token_api_v1_xiaohongshu_web_get_note_id_and_xsec_token_get_0

        通过分享链接获取小红书的Note ID 和 xsec_token/Get Xiaohongshu Note ID and xsec_token by share link  # noqa: E501
        """
        pass

    def test_get_note_info_v1_api_v1_xiaohongshu_web_get_note_info_get(self):
        """Test case for get_note_info_v1_api_v1_xiaohongshu_web_get_note_info_get

        获取笔记信息 V1/Get note info V1  # noqa: E501
        """
        pass

    def test_get_note_info_v1_api_v1_xiaohongshu_web_get_note_info_get_0(self):
        """Test case for get_note_info_v1_api_v1_xiaohongshu_web_get_note_info_get_0

        获取笔记信息 V1/Get note info V1  # noqa: E501
        """
        pass

    def test_get_note_info_v2_api_v1_xiaohongshu_web_get_note_info_v2_get(self):
        """Test case for get_note_info_v2_api_v1_xiaohongshu_web_get_note_info_v2_get

        获取笔记信息 V2/Get note info V2  # noqa: E501
        """
        pass

    def test_get_note_info_v2_api_v1_xiaohongshu_web_get_note_info_v2_get_0(self):
        """Test case for get_note_info_v2_api_v1_xiaohongshu_web_get_note_info_v2_get_0

        获取笔记信息 V2/Get note info V2  # noqa: E501
        """
        pass

    def test_get_note_info_v3_api_v1_xiaohongshu_web_get_note_info_v3_get(self):
        """Test case for get_note_info_v3_api_v1_xiaohongshu_web_get_note_info_v3_get

        获取笔记信息 V3 (游客)/Get note info V3 (Visitor)  # noqa: E501
        """
        pass

    def test_get_note_info_v3_api_v1_xiaohongshu_web_get_note_info_v3_get_0(self):
        """Test case for get_note_info_v3_api_v1_xiaohongshu_web_get_note_info_v3_get_0

        获取笔记信息 V3 (游客)/Get note info V3 (Visitor)  # noqa: E501
        """
        pass

    def test_get_note_info_v4_api_v1_xiaohongshu_web_get_note_info_v4_get(self):
        """Test case for get_note_info_v4_api_v1_xiaohongshu_web_get_note_info_v4_get

        获取笔记信息 V4/Get note info V4  # noqa: E501
        """
        pass

    def test_get_note_info_v4_api_v1_xiaohongshu_web_get_note_info_v4_get_0(self):
        """Test case for get_note_info_v4_api_v1_xiaohongshu_web_get_note_info_v4_get_0

        获取笔记信息 V4/Get note info V4  # noqa: E501
        """
        pass

    def test_get_note_info_v5_api_v1_xiaohongshu_web_get_note_info_v5_post(self):
        """Test case for get_note_info_v5_api_v1_xiaohongshu_web_get_note_info_v5_post

        获取笔记信息 V5 (自带Cookie)/Get note info V5 (Self-provided Cookie)  # noqa: E501
        """
        pass

    def test_get_note_info_v5_api_v1_xiaohongshu_web_get_note_info_v5_post_0(self):
        """Test case for get_note_info_v5_api_v1_xiaohongshu_web_get_note_info_v5_post_0

        获取笔记信息 V5 (自带Cookie)/Get note info V5 (Self-provided Cookie)  # noqa: E501
        """
        pass

    def test_get_user_info_api_v1_xiaohongshu_web_get_user_info_get(self):
        """Test case for get_user_info_api_v1_xiaohongshu_web_get_user_info_get

        获取用户信息 V1/Get user info V1  # noqa: E501
        """
        pass

    def test_get_user_info_api_v1_xiaohongshu_web_get_user_info_get_0(self):
        """Test case for get_user_info_api_v1_xiaohongshu_web_get_user_info_get_0

        获取用户信息 V1/Get user info V1  # noqa: E501
        """
        pass

    def test_get_user_info_v2_api_v1_xiaohongshu_web_get_user_info_v2_get(self):
        """Test case for get_user_info_v2_api_v1_xiaohongshu_web_get_user_info_v2_get

        获取用户信息 V2/Get user info V2  # noqa: E501
        """
        pass

    def test_get_user_info_v2_api_v1_xiaohongshu_web_get_user_info_v2_get_0(self):
        """Test case for get_user_info_v2_api_v1_xiaohongshu_web_get_user_info_v2_get_0

        获取用户信息 V2/Get user info V2  # noqa: E501
        """
        pass

    def test_get_user_info_v3_api_v1_xiaohongshu_web_get_user_info_v3_get(self):
        """Test case for get_user_info_v3_api_v1_xiaohongshu_web_get_user_info_v3_get

        获取用户信息 V3/Get user info V3  # noqa: E501
        """
        pass

    def test_get_user_info_v3_api_v1_xiaohongshu_web_get_user_info_v3_get_0(self):
        """Test case for get_user_info_v3_api_v1_xiaohongshu_web_get_user_info_v3_get_0

        获取用户信息 V3/Get user info V3  # noqa: E501
        """
        pass

    def test_get_user_notes_api_v1_xiaohongshu_web_get_user_notes_get(self):
        """Test case for get_user_notes_api_v1_xiaohongshu_web_get_user_notes_get

        获取用户的笔记 V1/Get user notes V1  # noqa: E501
        """
        pass

    def test_get_user_notes_api_v1_xiaohongshu_web_get_user_notes_get_0(self):
        """Test case for get_user_notes_api_v1_xiaohongshu_web_get_user_notes_get_0

        获取用户的笔记 V1/Get user notes V1  # noqa: E501
        """
        pass

    def test_get_user_notes_api_v1_xiaohongshu_web_get_user_notes_v2_get(self):
        """Test case for get_user_notes_api_v1_xiaohongshu_web_get_user_notes_v2_get

        获取用户的笔记 V2/Get user notes V2  # noqa: E501
        """
        pass

    def test_get_user_notes_api_v1_xiaohongshu_web_get_user_notes_v2_get_0(self):
        """Test case for get_user_notes_api_v1_xiaohongshu_web_get_user_notes_v2_get_0

        获取用户的笔记 V2/Get user notes V2  # noqa: E501
        """
        pass

    def test_get_visitor_cookie_api_v1_xiaohongshu_web_get_visitor_cookie_get(self):
        """Test case for get_visitor_cookie_api_v1_xiaohongshu_web_get_visitor_cookie_get

        获取游客Cookie/Get visitor cookie  # noqa: E501
        """
        pass

    def test_get_visitor_cookie_api_v1_xiaohongshu_web_get_visitor_cookie_get_0(self):
        """Test case for get_visitor_cookie_api_v1_xiaohongshu_web_get_visitor_cookie_get_0

        获取游客Cookie/Get visitor cookie  # noqa: E501
        """
        pass

    def test_search_notes_api_v1_xiaohongshu_web_search_notes_get(self):
        """Test case for search_notes_api_v1_xiaohongshu_web_search_notes_get

        搜索笔记/Search notes  # noqa: E501
        """
        pass

    def test_search_notes_api_v1_xiaohongshu_web_search_notes_get_0(self):
        """Test case for search_notes_api_v1_xiaohongshu_web_search_notes_get_0

        搜索笔记/Search notes  # noqa: E501
        """
        pass

    def test_search_users_api_v1_xiaohongshu_web_search_users_get(self):
        """Test case for search_users_api_v1_xiaohongshu_web_search_users_get

        搜索用户/Search users  # noqa: E501
        """
        pass

    def test_search_users_api_v1_xiaohongshu_web_search_users_get_0(self):
        """Test case for search_users_api_v1_xiaohongshu_web_search_users_get_0

        搜索用户/Search users  # noqa: E501
        """
        pass

    def test_sign_api_v1_xiaohongshu_web_sign_post(self):
        """Test case for sign_api_v1_xiaohongshu_web_sign_post

        小红书Web签名/Xiaohongshu Web sign  # noqa: E501
        """
        pass

    def test_sign_api_v1_xiaohongshu_web_sign_post_0(self):
        """Test case for sign_api_v1_xiaohongshu_web_sign_post_0

        小红书Web签名/Xiaohongshu Web sign  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
