# coding: utf-8

"""
    TikHub.io - Your Ultimate Social Media Data & API Marketplace

    High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from tikhub_sdk_v2.configuration import Configuration


class BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'page': 'int',
        'page_size': 'int',
        'date_window': 'int',
        'tags': 'list[object]'
    }

    attribute_map = {
        'page': 'page',
        'page_size': 'page_size',
        'date_window': 'date_window',
        'tags': 'tags'
    }

    def __init__(self, page=1, page_size=10, date_window=24, tags=None, local_vars_configuration=None):  # noqa: E501
        """BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._page = None
        self._page_size = None
        self._date_window = None
        self._tags = None
        self.discriminator = None

        if page is not None:
            self.page = page
        if page_size is not None:
            self.page_size = page_size
        if date_window is not None:
            self.date_window = date_window
        if tags is not None:
            self.tags = tags

    @property
    def page(self):
        """Gets the page of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.  # noqa: E501

        Page，页码  # noqa: E501

        :return: The page of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.  # noqa: E501
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.

        Page，页码  # noqa: E501

        :param page: The page of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.  # noqa: E501
        :type: int
        """

        self._page = page

    @property
    def page_size(self):
        """Gets the page_size of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.  # noqa: E501

        Page Size，每页数量  # noqa: E501

        :return: The page_size of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.

        Page Size，每页数量  # noqa: E501

        :param page_size: The page_size of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    @property
    def date_window(self):
        """Gets the date_window of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.  # noqa: E501

        Date Window，时间窗口，1 按小时 2 按天  # noqa: E501

        :return: The date_window of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.  # noqa: E501
        :rtype: int
        """
        return self._date_window

    @date_window.setter
    def date_window(self, date_window):
        """Sets the date_window of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.

        Date Window，时间窗口，1 按小时 2 按天  # noqa: E501

        :param date_window: The date_window of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.  # noqa: E501
        :type: int
        """

        self._date_window = date_window

    @property
    def tags(self):
        """Gets the tags of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.  # noqa: E501

        Tags，子级垂类标签，空则为全部，多个标签需传入{\"value\": \"{顶级垂类标签id}\", \"children\": [{\"value\": \"{子级垂类标签id}\"}, {\"value\": \"{子级垂类标签id}\"}]}  # noqa: E501

        :return: The tags of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.  # noqa: E501
        :rtype: list[object]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.

        Tags，子级垂类标签，空则为全部，多个标签需传入{\"value\": \"{顶级垂类标签id}\", \"children\": [{\"value\": \"{子级垂类标签id}\"}, {\"value\": \"{子级垂类标签id}\"}]}  # noqa: E501

        :param tags: The tags of this BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost.  # noqa: E501
        :type: list[object]
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BodyFetchHotTotalLowFanListApiV1DouyinBillboardFetchHotTotalLowFanListPost):
            return True

        return self.to_dict() != other.to_dict()
